import { Platform, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: { flex: 1 },
    header: { paddingTop: 0, paddingBottom: 8, paddingHorizontal: 16, flexDirection: 'row', justifyContent: 'space-between' },
    headerShell: { borderBottomWidth: 1, paddingBottom: 4, zIndex: 1 },
    headerExtras: { gap: 4, paddingBottom: 2 },
    filterOverlay: { position: 'absolute', left: 12, right: 12, borderRadius: 14, borderWidth: 1, overflow: 'hidden', zIndex: 3 },
    filterSummaryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 4, paddingHorizontal: 10 },
    filterSummaryLeft: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    filterSummaryText: { fontSize: 11, fontWeight: '700' },
    headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1 },
    headerRight: { flexDirection: 'row', gap: 8 },
    userName: { fontSize: 15, fontWeight: '700', maxWidth: 100 },
    verifiedBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 12, borderWidth: 1, gap: 4 },
    verifiedText: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
    balanceMini: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    headerButton: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    skeletonName: { width: 80, height: 16, borderRadius: 4 },
    sectionToggle: { flexDirection: 'row', borderWidth: 1, borderRadius: 14, padding: 4, marginHorizontal: 12, marginTop: 6, marginBottom: 4 },
    sectionBtn: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 12 },
    sectionBtnText: { fontSize: 12, fontWeight: '700' },
    filterBar: { paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderRadius: 16, marginHorizontal: 12 },
    filterBarRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    filterToggleBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, height: 34, borderRadius: 999, borderWidth: 1 },
    filterScroll: { flex: 1 },
    filterScrollContent: { gap: 6 },
    filterRoll: { overflow: 'hidden', marginTop: 8 },
    filterPanel: { overflow: 'hidden' },
    filterPanelInner: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 4, paddingHorizontal: 8 },
    // Clear filters button - outline style with X icon
    clearFiltersBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, height: 26, borderRadius: 999, borderWidth: 1, backgroundColor: 'transparent' },
    clearFiltersBtnText: { fontSize: 10, fontWeight: '600', textTransform: 'uppercase' },
    dropdownWrapper: { position: 'relative' },
    dropdownButton: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, height: 28, borderRadius: 10, borderWidth: 1 },
    dropdownLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
    dropdownOverlay: { flex: 1, backgroundColor: 'transparent' },
    dropdownMenu: { position: 'absolute', borderRadius: 8, borderWidth: 1, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 12, elevation: 8, overflow: 'hidden' },
    dropdownItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 14 },
    dropdownItemText: { fontSize: 13, fontWeight: '500' },
    checkIconWrapper: { width: 20, alignItems: 'center', marginRight: 6 },
    list: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 0 },
    listWithFiltersOpen: { paddingTop: 64 },
    listWithFiltersClosed: { paddingTop: 24 },
    colWrapper: { justifyContent: 'space-between' },
    center: { flex: 1, alignItems: 'center', justifyContent: 'center', minHeight: 300 },
    orderCard: {
        borderRadius: 18,
        borderWidth: 1,
        marginBottom: 14,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
    },
    cardContent: { flex: 1, padding: 14, gap: 2 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 },
    serviceType: { fontSize: 16, fontWeight: '700', flex: 1, paddingRight: 6 },
    cardPrice: { fontSize: 16, fontWeight: '700' },
    cardMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8, flexWrap: 'wrap' },
    urgencyBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, borderWidth: 1 },
    urgencyText: { fontSize: 9, fontWeight: '700', textTransform: 'uppercase' },
    pricingBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, borderWidth: 1, maxWidth: '40%' },
    pricingText: { fontSize: 9, fontWeight: '700', textTransform: 'uppercase' },
    locationContainer: { flexDirection: 'row', alignItems: 'center', gap: 4, flex: 1 },
    locationText: { fontSize: 12, flex: 1 },
    description: { fontSize: 13, marginBottom: 8, lineHeight: 18 },
    plannedRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8, borderRadius: 10, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 7 },
    plannedLabel: { fontSize: 11, fontWeight: '600' },
    plannedText: { fontSize: 14, flex: 1, lineHeight: 20, fontWeight: '600' },
    inlineHintRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8 },
    inlineHintLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
    inlineHintValue: { fontSize: 13, flex: 1, lineHeight: 18 },
    cardInfoBlock: { borderRadius: 12, borderWidth: 1, padding: 10, gap: 6, marginBottom: 10 },
    cardInfoRow: { gap: 3 },
    cardInfoLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
    cardInfoValue: { fontSize: 14, lineHeight: 20 },
    copyAddressBtn: { alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 6, borderRadius: 999, borderWidth: 1 },
    copyAddressText: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
    clientInfo: { paddingTop: 10, borderTopWidth: 1, gap: 4 },
    clientRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    clientLabel: { fontSize: 12 },
    clientPhone: { fontSize: 12, fontWeight: '600' },
    cardActions: { marginTop: 12 },
    actionRow: { flexDirection: 'row', gap: 8 },
    actionButton: {
        paddingVertical: 12,
        paddingHorizontal: 14,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
    },
    actionButtonText: { color: '#fff', fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
    outlineButton: {
        paddingVertical: 11,
        paddingHorizontal: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        backgroundColor: 'transparent',
    },
    outlineButtonText: { fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
    pendingBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 8, gap: 4 },
    pendingText: { fontSize: 11, fontStyle: 'italic' },
    bottomBar: { position: 'absolute', bottom: 0, left: 0, right: 0, flexDirection: 'row', paddingBottom: Platform.OS === 'ios' ? 24 : 10, paddingTop: 10, borderTopWidth: 1 },
    tabBtn: { flex: 1, alignItems: 'center', gap: 4 },
    tabLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
    accountContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 16 },
    balanceCard: { padding: 20, borderRadius: 16, borderWidth: 1, marginBottom: 16, alignItems: 'center' },
    balanceHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
    balanceLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase' },
    balanceValue: { fontSize: 36, fontWeight: '200' },
    blockedBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, marginTop: 8 },
    accountHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
    accountBackBtn: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
    accountHeaderTitle: { fontSize: 16, fontWeight: '700' },
    accountMenu: { gap: 10 },
    accountMenuItem: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12, paddingHorizontal: 14, borderRadius: 14, borderWidth: 1 },
    accountMenuIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    accountMenuLabel: { flex: 1, fontSize: 13, fontWeight: '600' },
    earningsSection: {},
    periodFilter: { flexDirection: 'row', gap: 8, marginBottom: 16 },
    periodChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, borderWidth: 1 },
    statCard: { padding: 20, borderRadius: 12, borderWidth: 1, marginBottom: 12, alignItems: 'center' },
    statCardSmall: { width: '48%', padding: 14, borderRadius: 12, borderWidth: 1 },
    statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 16 },
    statHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
    statLabel: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
    statValue: { fontSize: 28, fontWeight: '200' },
    statValueSmall: { fontSize: 18, fontWeight: '300' },
    earningsList: { borderRadius: 12, borderWidth: 1 },
    earningItem: { flexDirection: 'row', justifyContent: 'space-between', padding: 14 },
    earningService: { fontSize: 13, fontWeight: '600' },
    historySection: { gap: 10 },
    historyFilterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
    historyFilterChip: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 999, borderWidth: 1 },
    historySortRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
    historySortChip: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 999, borderWidth: 1 },
    limitsCard: { borderWidth: 1, borderRadius: 14, padding: 10, marginBottom: 12, gap: 6 },
    limitsTitle: { fontSize: 12, fontWeight: '700' },
    limitsRow: { flexDirection: 'row', gap: 8 },
    limitBadge: { flex: 1, borderWidth: 1, borderRadius: 10, paddingVertical: 6, paddingHorizontal: 10, gap: 2 },
    limitBadgeLabel: { fontSize: 10, fontWeight: '600' },
    limitBadgeValue: { fontSize: 14, fontWeight: '700' },
    historyTable: { borderWidth: 1, borderRadius: 12, overflow: 'hidden' },
    historyRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 12, borderTopWidth: 1 },
    historyHeaderRow: { borderTopWidth: 0 },
    historyGroupHeader: { paddingVertical: 8, paddingHorizontal: 12, borderTopWidth: 1 },
    historyGroupHeaderText: { fontSize: 11, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.4 },
    historyCell: { fontSize: 11 },
    historyCellType: { flex: 1.6, fontWeight: '700' },
    historyCellDetails: { flex: 1.6 },
    historyCellAmount: { flex: 0.8, alignItems: 'flex-start' },
    historyItem: { flexDirection: 'row', justifyContent: 'space-between', padding: 14, borderRadius: 10, borderWidth: 1 },
    statusBadgeSmall: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, marginTop: 4 },
    emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
    paginationBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingVertical: 12, paddingHorizontal: 16, borderTopWidth: 1, marginTop: 8 },
    paginationBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 999, borderWidth: 1 },
    paginationInfo: { fontSize: 11, fontWeight: '600' },
    profileSection: { gap: 16 },
    profileCard: { padding: 16, borderRadius: 12, borderWidth: 1 },
    // Profile header row with name and verified badge
    profileHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    verifiedBadgeProfile: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, borderWidth: 1 },
    profileName: { fontSize: 18, fontWeight: '700' },
    statsRow: { flexDirection: 'row', gap: 10 },
    statItem: { flex: 1, alignItems: 'center', padding: 16, borderRadius: 12, gap: 4 },
    infoRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
    modalContent: { width: '100%', maxWidth: 500, borderRadius: 16, padding: 20, maxHeight: '80%' },
    modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 20, textAlign: 'center' },
    modalLabel: { fontSize: 12, fontWeight: '600', marginBottom: 8, textTransform: 'uppercase' },
    modalInput: { borderWidth: 1, borderRadius: 8, padding: 12, marginBottom: 12, fontSize: 14 },
    modalActions: { flexDirection: 'row', gap: 10, marginTop: 20 },
    modalButton: { flex: 1, paddingVertical: 12, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
    modalButtonText: { color: '#fff', fontSize: 13, fontWeight: '700', textTransform: 'uppercase' },
    reasonItem: { padding: 12, borderRadius: 8, borderWidth: 1, marginBottom: 8 },
    claimOverlay: { padding: 0, alignItems: 'stretch', justifyContent: 'flex-end' },
    claimModalContent: {
        width: '100%',
        maxWidth: '100%',
        alignSelf: 'stretch',
        flex: 1,
        maxHeight: '100%',
        padding: 0,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
        overflow: 'hidden',
        paddingTop: 6,
        paddingHorizontal: 18,
        paddingBottom: 0
    },
    claimHandle: { alignSelf: 'center', width: 48, height: 5, borderRadius: 999, backgroundColor: 'rgba(148,163,184,0.5)', marginBottom: 6 },
    claimScroll: { paddingBottom: 12 },
    claimHeader: { alignItems: 'center', gap: 10, marginBottom: 6 },
    claimHeaderRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 6, position: 'relative' },
    claimHeaderText: { flex: 1, alignItems: 'center' },
    claimCloseBtn: { position: 'absolute', right: 0, top: 0, width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
    claimCloseText: { fontSize: 18, fontWeight: '700' },
    sheetContent: { flex: 1, position: 'relative', justifyContent: 'flex-start' },
    sheetBody: { flex: 1 },
    sheetBodyContent: { gap: 6 },
    sheetHeaderBlock: { marginTop: 16, marginBottom: 20 },
    claimTitle: { fontSize: 22, fontWeight: '700', textAlign: 'center' },
    claimSubtitle: { fontSize: 13, textAlign: 'center', marginBottom: 16, lineHeight: 18 },
    claimDetails: { borderRadius: 16, borderWidth: 1, padding: 12, gap: 10, marginBottom: 12 },
    claimRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    claimLabel: { fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.4 },
    claimValue: { fontSize: 16, fontWeight: '600', lineHeight: 22 },
    claimWarningBox: { marginTop: 6, gap: 4 },
    claimActions: { position: 'absolute', left: 18, right: 18, bottom: 16, flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    claimButton: { flex: 1, paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    claimButtonText: { fontSize: 13, fontWeight: '700', textTransform: 'uppercase', color: '#fff' },
    sheetSubTitle: { fontSize: 12, marginTop: 2, lineHeight: 16, textAlign: 'center' },
    sheetHeroRow: { flexDirection: 'row', gap: 8 },
    sheetHeroCard: { flex: 1, borderRadius: 16, padding: 12, gap: 6, borderWidth: 1 },
    sheetHeroLabel: { fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.6, marginBottom: 6 },
    sheetValueBase: { fontSize: 18, lineHeight: 24 },
    sheetValuePrimary: { fontWeight: '400' },
    sheetValueSecondary: { fontWeight: '400' },
    sheetValuePhone: { fontWeight: '400' },
    sheetMetaInline: { fontSize: 11, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.4 },
    sheetMetaRow: { flexDirection: 'row', gap: 8, marginTop: 4 },
    sheetMetaCard: { flex: 1, borderRadius: 14, padding: 10, gap: 6, borderWidth: 1 },
    sheetMetaLabel: { fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.4, marginBottom: 6 },
    sheetMetaValue: { fontSize: 18, fontWeight: '400', lineHeight: 24 },
    sheetLabel: { fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.4 },
    sheetValue: { fontSize: 18, fontWeight: '400', lineHeight: 24 },
    sheetStatusPill: { alignSelf: 'center', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999, marginLeft: 8 },
    sheetStatusText: { fontSize: 12, fontWeight: '700' },
    sheetTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    sheetDetailsBlock: { marginTop: 6, gap: 6 },
    sheetDetailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
    sheetDetailMain: { flex: 1, gap: 4 },
    sheetDetailSide: { flex: 1, gap: 6, alignItems: 'flex-start' },
    sheetInlineActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
    sheetInlineBtn: { borderWidth: 1, borderRadius: 10, paddingVertical: 6, paddingHorizontal: 10, alignSelf: 'flex-start' },
    sheetInlineText: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
    sheetInfoCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, borderRadius: 16, padding: 12, borderWidth: 1 },
    sheetInfoMain: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, flex: 1 },
    sheetInfoText: { flex: 1, gap: 1 },
    sheetInfoLabel: { fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.4, marginBottom: 6 },
    sheetInfoValue: { fontSize: 18, fontWeight: '400', lineHeight: 24 },
    sheetAddressBlock: { gap: 10 },
    sheetFieldBlock: { gap: 4 },
    sheetFieldLabel: { fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.4, marginBottom: 2 },
    sheetInfoActions: { flexDirection: 'row', gap: 8 },
    sheetPhoneRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginTop: 4 },
    sheetIconBtn: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
    sheetFooter: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopWidth: 1, paddingTop: 10, paddingHorizontal: 18 },
    sheetFooterActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    primarySheetButton: {
        flex: 1,
        paddingVertical: 16,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 10,
        elevation: 6,
    },
    primarySheetButtonText: { fontSize: 13, fontWeight: '800', textTransform: 'uppercase', color: '#fff' },
    secondarySheetButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 14,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        elevation: 4,
    },
    secondarySheetButtonText: { fontSize: 12, fontWeight: '700', textTransform: 'uppercase' },
    sheetPeek: {
        position: 'absolute',
        left: 16,
        right: 16,
        bottom: 76,
        borderRadius: 16,
        paddingVertical: 12,
        paddingHorizontal: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        borderWidth: 1,
        shadowColor: '#000',
        shadowOpacity: 0.16,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 8,
    },
    sheetPeekLeft: { flex: 1, gap: 4 },
    sheetPeekTopRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    sheetPeekLabel: { fontSize: 11, textTransform: 'uppercase', fontWeight: '700', letterSpacing: 0.4 },
    sheetPeekValue: { fontSize: 16, fontWeight: '700' },
    sheetPeekStatusPill: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999 },
    sheetPeekStatusText: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase' },
    sheetPeekChevron: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
    sheetModalRoot: { flex: 1, justifyContent: 'flex-end', zIndex: 999, elevation: 30 },
    sheetBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15,23,42,0.5)', zIndex: 1 },
    sheetContainer: { width: '100%', zIndex: 2 },
    settingsSection: { gap: 12 },
    settingsCard: { borderRadius: 14, borderWidth: 1, padding: 14 },
    settingsTitle: { fontSize: 13, fontWeight: '700', marginBottom: 10 },
    settingsOptionsRow: { flexDirection: 'row', gap: 8 },
    settingsOption: { flex: 1, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 12, borderWidth: 1, minWidth: 64, alignItems: 'center', justifyContent: 'center', gap: 4 },
    settingsToggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    settingsToggle: { width: 48, height: 26, borderRadius: 999, justifyContent: 'center' },
    settingsToggleThumb: { position: 'absolute', width: 20, height: 20, borderRadius: 10, backgroundColor: '#fff' },
    settingsSupportList: { gap: 8, marginTop: 4 },
    settingsSupportRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 12, borderWidth: 1 },
    settingsSupportLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    settingsSupportLabel: { fontSize: 12, fontWeight: '600' },
    settingsSupportValue: { fontSize: 11 },
    skeletonCard: { borderRadius: 18, borderWidth: 1, padding: 14, marginBottom: 14 },
    skeletonHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    skeletonMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
    skeletonDesc: { gap: 6, marginBottom: 10 },
    skeletonInfoBlock: { borderRadius: 12, padding: 10, gap: 6, backgroundColor: 'rgba(148,163,184,0.12)' },
    skeletonAction: { height: 36, borderRadius: 12, backgroundColor: 'rgba(148,163,184,0.25)', marginTop: 12 },
    skeletonLineWide: { height: 14, borderRadius: 8, width: '55%', backgroundColor: 'rgba(148,163,184,0.25)' },
    skeletonLineShort: { height: 14, borderRadius: 8, width: '20%', backgroundColor: 'rgba(148,163,184,0.25)' },
    skeletonBadge: { height: 18, borderRadius: 999, width: 70, backgroundColor: 'rgba(148,163,184,0.22)' },
    skeletonLineTiny: { height: 10, borderRadius: 6, width: 90, backgroundColor: 'rgba(148,163,184,0.22)' },
    skeletonLineFull: { height: 10, borderRadius: 6, width: '100%', backgroundColor: 'rgba(148,163,184,0.22)' },
    skeletonLineMid: { height: 10, borderRadius: 6, width: '70%', backgroundColor: 'rgba(148,163,184,0.22)' },
});

export { styles };
