const freeAnalytics = `COMPLETED_STATUSES
DAY_MS
Platform
SCREEN_WIDTH
TRANSLATIONS
URGENCY_OPTIONS
analyticsAreaOptions
analyticsChartSeries
analyticsCustomRange
analyticsDailySeries
analyticsDetail
analyticsDispatcherId
analyticsDispatcherOptions
analyticsDispatcherStats
analyticsDispatchers
analyticsFilters
analyticsGranularity
analyticsInfoHandlers
analyticsLists
analyticsLocale
analyticsMasterId
analyticsMasterOptions
analyticsMasterStats
analyticsPeople
analyticsRange
analyticsSection
analyticsStats
analyticsTooltip
analyticsTrendTooltip
dispatcherCreatedMeta
dispatcherCreatedSeries
dispatcherHandledMeta
dispatcherHandledSeries
dispatcherStatusBreakdown
dispatcherTrendWindow
formatMoney
formatNumber
formatPercent
formatShortDate
getAnalyticsColumns
getPointerPos
hideAnalyticsTrendTooltip
hidePriceDistTooltip
isDark
isWeb
masterCompletedMeta
masterCompletedSeries
masterRevenueMeta
masterRevenueSeries
masterStatusBreakdown
masterTrendWindow
normalizeStatus
openAnalyticsOrdersModal
priceDistChartWidth
priceDistData
priceDistGrouping
priceDistGroupingNotice
priceDistGroupingRules
priceDistRange
priceDistScope
priceDistTooltip
renderHeader
serviceFilterOptions
setAnalyticsCustomRange
setAnalyticsDetail
setAnalyticsDispatcherId
setAnalyticsFilters
setAnalyticsGranularity
setAnalyticsMasterId
setAnalyticsRange
setAnalyticsSection
setPickerModal
setPriceDistChartWidth
setPriceDistGrouping
setPriceDistRange
setPriceDistScope
setShowAnalyticsEndPicker
setShowAnalyticsStartPicker
showAnalyticsEndPicker
showAnalyticsStartPicker
showAnalyticsTrendTooltip
showPriceDistTooltip
styles
updateAnalyticsTrendTooltipPos
updatePriceDistTooltipPos`.split('\n');

const excludeA = new Set(['COMPLETED_STATUSES','DAY_MS','Platform','SCREEN_WIDTH','URGENCY_OPTIONS','formatMoney','formatNumber','formatPercent','formatShortDate','getAnalyticsColumns','getPointerPos','normalizeStatus']);

const passA = freeAnalytics.filter(x=>x && !excludeA.has(x) && x!=='undefined');
console.log('A pass count', passA.length);
console.log(passA.join('\n'));

const freeOrders = `ATTENTION_FILTER_OPTIONS
STATUS_COLORS
TRANSLATIONS
filterAttentionType
filteredOrders
getOrderStatusLabel
getServiceLabel
getTimeAgo
isDark
needsActionCount
needsActionOrders
onRefresh
openAssignModalFromQueue
openOrderDetails
queueLoading
queuePage
queueTotalCount
refreshing
renderFilters
renderHeader
setFilterAttentionType
setPickerModal
setQueuePage
setShowNeedsAttention
setSortOrder
showNeedsAttention
sortOrder
styles
t
viewMode`.split('\n');
const excludeO = new Set(['ATTENTION_FILTER_OPTIONS','STATUS_COLORS','getOrderStatusLabel','getServiceLabel','getTimeAgo']);
const passO = freeOrders.filter(x=>x && !excludeO.has(x));
console.log('---');
console.log('O pass count', passO.length);
console.log(passO.join('\n'));
