import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const translations = {
    en: {
        // General
        welcome: "Welcome",
        loading: "Loading...",
        cancel: "Cancel",
        save: "Save",
        clear: "Clear",
        confirm: "Confirm",
        close: "Close",
        back: "Back",
        next: "Next",
        ok: "OK",
        yes: "Yes",
        no: "No",
        search: "Search...",
        noResults: "No results found",
        retry: "Retry",
        refresh: "Refresh",

        // Auth & User
        verified: "Verified",
        unverified: "Unverified",
        online: "Online",
        offline: "Offline",
        logout: "Logout",
        logoutConfirm: "Are you sure you want to logout?",        // Login
        loginTitle: "Partner Login",
        loginEmail: "Email",
        loginEmailPlaceholder: "email@example.com",
        loginPassword: "Password",
        loginPasswordPlaceholder: "********",
        loginButton: "Sign In",
        loginSupport: "Support",
        loginFooter: "(c) 2024 Master.kg",
        loginErrorGeneric: "An unexpected error occurred",
        loginErrorInvalidCredentials: "Invalid email or password",
        loginSuccess: "Login successful!",

        // Tabs & Navigation
        tabOrders: "Orders",
        tabMyAccount: "My Account",
        tabCreate: "Create",
        tabQueue: "Queue",
        tabOverview: "Overview",
        tabPeople: "People",
        tabSettings: "Settings",

        // Dashboard Sections
        sectionAvailable: "Available Orders",
        sectionMyJobs: "My Jobs",
        sectionEarnings: "Earnings",
        sectionHistory: "History",
        sectionProfile: "Profile",
        sectionSettings: "Settings",
        sectionClient: "Client",
        sectionMaster: "Master",
        sectionDetails: "Order Details",
        sectionFinancials: "Financials",
        sectionNote: "Internal Note",

        // Settings (Master)
        settingsLanguage: "Language",
        settingsTheme: "Theme",
        settingsThemeHint: "Adjust appearance",
        settingsSupport: "Support",
        settingsSupportPhone: "Call Support",
        settingsSupportWhatsApp: "WhatsApp",
        settingsSupportTelegram: "Telegram",

        // Filters
        filterUrgency: "Urgency",
        filterService: "Service",
        filterArea: "Area",
        filterAll: "All",
        filterClear: "Clear",
        filterStatus: "Status",
        filterSort: "Sort",
        filterNewestFirst: "Newest First",
        filterOldestFirst: "Oldest First",
        filterAllOrders: "All Orders",
        filterMyOrders: "My Orders",
        filterAllUrgency: "All Urgency",
        hideFilters: "Hide Filters",
        showFilters: "Show Filters",

        // Admin
        adminTitle: "Admin Pro",
        peopleMasters: "Masters",
        peopleDispatchers: "Dispatchers",
        settingsTitle: "Platform Settings",
        basePayout: "Default Call-out Fee",
        commissionRate: "Commission Rate",
        priceDeviation: "Price Deviation",
        autoClaimTimeout: "Auto-Claim Timeout",
        orderExpiry: "Order Expiry",
        serviceTypes: "Service Types",
        addType: "Add Type",
        revenueTrend: "Revenue Trend",
        commissionCollection: "Commission Collection",
        // Admin Settings Extended
        configurationTitle: "Configuration",
        configurationSubtitle: "Platform-wide settings and parameters",
        serviceTypesTitle: "Service Types",
        serviceTypesSubtitle: "Manage available service categories",
        addServiceType: "Add Service Type",
        editServiceType: "Edit Service Type",
        createService: "Create Service",
        updateService: "Update Service",
        noServiceTypes: "No service types configured",
        addFirstService: "Add your first service type to get started",
        codeReadOnly: "Read-only",
        codeUnique: "Code (Unique ID)",
        localizedNames: "Localized Names",
        englishName: "English Name",
        russianName: "Russian Name",
        kyrgyzName: "Kyrgyz Name",
        editSettings: "Edit Settings",
        standardCallout: "Used when no call-out fee is set",
        platformCommission: "Platform commission percentage",
        thresholdAlerts: "Threshold for price alerts",
        minutesExpire: "Minutes before order expires",
        hoursExpire: "Hours until unclaimed orders expire",
        // People Management
        addMaster: "Add Master",
        addDispatcher: "Add Dispatcher",
        noMastersFound: "No masters found",
        noDispatchersFound: "No dispatchers found",
        topUp: "TOP UP",
        verify: "VERIFY",
        unverify: "UNVERIFY",
        activate: "ACTIVATE",
        deactivate: "DEACTIVATE",
        active: "Active",
        inactive: "Inactive",
        // Create Order Page
        createNewOrder: "Create New Order",
        clientPhoneRequired: "Client Phone *",
        districtRequired: "District *",
        fullAddressRequired: "Full Address *",
        problemRequired: "Problem Description *",
        describeIssue: "Describe the issue...",
        confirmDetails: "Confirm Details",
        // Details Drawer
        orderDetails: "Order Details",
        client: "CLIENT",
        addressSection: "ADDRESS",
        problemSection: "PROBLEM",
        editDetails: "Edit Details",
        saveChanges: "Save Changes",
        reopenOrder: "Reopen Order",
        forceAssignMaster: "Force Assign Master",
        reassignMaster: "Reassign Master",
        removeMaster: "Remove Master",
        confirmUnassignTitle: "Remove Master",
        confirmUnassignMsg: "Remove the assigned master and reopen this order?",
        paymentProofVerification: "PAYMENT PROOF VERIFICATION",
        badgePaymentProof: "Payment Proof",
        approve: "Approve",
        reject: "Reject",
        processing: "Processing...",
        selectMasterAssign: "Select a master to assign this order to:",
        noAvailableMasters: "No available masters found",
        // Modals
        recordCommissionPayment: "Record Commission Payment",
        master: "Master",
        amountSom: "Amount (сом)",
        confirmPayment: "Confirm Payment",
        saving: "Saving...",
        settingsSaved: "Settings saved",
        errorSavingSettings: "Error saving settings",
        // Balance
        balanceTopUp: "Balance Top-Up",
        addBalance: "Add Balance",
        searchOrders: "Search orders...",
        exit: "Exit",
        // Overview Stats
        totalOrders: "Total Orders",
        activeJobs: "Active Jobs",
        pending: "Pending",
        confirmed: "Confirmed",
        totalBalances: "Total Balances",
        lowBalance: "Low Balance",
        below500: "Below 500 сом",
        mastersCount: "masters",
        revenueTrendTitle: "Revenue Trend",
        selectedPeriod: "Selected Period",
        ordersByService: "Orders by Service",
        // Sidebar Navigation
        overview: "Overview",
        orders: "Orders",
        people: "People",
        settings: "Settings",
        // Person Details Drawer
        contactInfo: "CONTACT INFO",
        edit: "Edit",
        fullName: "Full Name",
        phone: "Phone",
        email: "Email",
        experienceYears: "Experience (years)",
        financials: "FINANCIALS",
        balance: "Balance:",
        performance: "PERFORMANCE",
        completedJobs: "Completed Jobs:",
        viewOrderHistory: "View Order History",
        topUpBalance: "Top Up Balance",
        unverifyMaster: "Unverify Master",
        verifyMaster: "Verify Master",
        resetPassword: "Reset Password",
        stats: "STATS",
        status: "Status:",
        created: "Created:",
        // Balance Modal
        addMasterBalance: "Add Master Balance",
        notesOptional: "Notes (optional)",
        // Status Badges
        verified: "VERIFIED",
        unverified: "UNVERIFIED",
        // Date Filter
        filterAll: "All",
        filterToday: "Today",
        filterWeek: "Week",
        filterMonth: "Month",
        filterCustom: "Custom",
        startDate: "Start:",
        endDate: "End:",
        selectDate: "Select date",
        // Service Type Sidebar
        modifyExistingService: "Modify existing service",
        createNewCategory: "Create a new service category",
        code: "Code:",
        // Reset Password Modal
        resetPasswordWarning: "This action will immediately change the user's password. They will need to use the new password to login.",
        newPassword: "New Password *",
        confirmPasswordLabel: "Confirm Password *",
        minCharacters: "Minimum 6 characters",
        reenterPassword: "Re-enter password",
        passwordsNotMatch: "Passwords do not match",
        resetting: "Resetting...",
        // Add User Modal
        createNewMasterAccount: "Create a new master account",
        createNewDispatcherAccount: "Create a new dispatcher account",
        emailRequired: "Email *",
        passwordRequired: "Password *",
        fullNameRequired: "Full Name *",
        phoneOptional: "Phone",
        serviceAreaOptional: "Service Area",
        experienceOptional: "Experience (years)",
        creating: "Creating...",
        createMaster: "Create Master",
        createDispatcher: "Create Dispatcher",
        // Order Time Labels
        justNow: "Just now",
        minsAgo: "m ago",
        hoursAgo: "h ago",
        daysAgo: "d ago",
        tapViewDetails: "Tap to view details",
        // Show Filters
        showFilters: "Show Filters",
        hideFilters: "Hide Filters",
        needsAttention: "Needs Attention",
        // Dashboard Charts
        ordersByService: "Orders by Service",
        orderStatus: "Order Status",
        commissionCollection: "Commission Collection",
        allTime: "All Time",
        collected: "Collected",
        outstanding: "Outstanding",
        chartNew: "New",
        chartClaimed: "Clm",
        chartWIP: "WIP",
        chartDone: "Done",
        chartPaid: "Paid",
        chartCanceled: "Can",

        // Service Types
        servicePlumbing: "Plumbing",
        serviceElectrician: "Electrician",
        serviceCleaning: "Cleaning",
        serviceCarpenter: "Carpenter",
        serviceRepair: "Repair",
        serviceInstallation: "Installation",
        serviceMaintenance: "Maintenance",
        serviceOther: "Other",
        serviceApplianceRepair: "Appliance Repair",
        serviceBuilding: "Building",
        serviceInspection: "Inspection",
        serviceHvac: "HVAC",
        servicePainting: "Painting",
        serviceFlooring: "Flooring",
        serviceRoofing: "Roofing",
        serviceLandscaping: "Landscaping",

        // Urgency
        urgencyEmergency: "Emergency",
        urgencyUrgent: "Urgent",
        urgencyPlanned: "Planned",

        // Status
        statusPlaced: "Placed",
        statusClaimed: "Claimed",
        statusStarted: "Started",
        statusCompleted: "Completed",
        statusConfirmed: "Confirmed",
        statusCanceled: "Canceled",
        statusCanceledByMaster: "Canceled by Master",
        statusCanceledByClient: "Canceled by Client",
        statusReopened: "Reopened",
        statusExpired: "Expired",
        statusActive: "Active",
        statusPayment: "Awaiting Payment",
        statusDisputed: "Disputed",
        statusAll: "All Orders",

        // Actions
        actionClaim: "Claim",
        actionLocked: "Locked",
        actionStart: "Start Job",
        actionCancel: "Refuse",
        actionComplete: "Complete",
        actionBack: "Back",
        actionSubmit: "Submit",
        actionEdit: "Edit",
        actionSave: "Save",
        actionDelete: "Delete",
        actionAssign: "Assign",
        actionUnassign: "Remove Master",
        actionReopen: "Reopen",
        actionPay: "Pay",
        actionCall: "Call",
        actionCopy: "Copy",
        actionCopyAddress: "Copy address",
        actionCopyPhone: "Copy phone",
        actionClose: "Close",
        actionCopyAddress: "Copy address",
        actionCopyPhone: "Copy phone",

        // Cards
        cardStartToSeeAddress: "Start job to see address",
        cardPendingApproval: "Pending Approval",
        cardUnassigned: "Unassigned",
        cardStuck: "Stuck",
        activeOrderTitle: "Active order",

        // Order Details
        clientName: "Client Name",
        clientPhone: "Client Phone",
        address: "Address",
        fullAddress: "Full Address",
        district: "District",
        description: "Description",
        problemDescription: "Problem Description",
        serviceType: "Service Type",
        price: "Price",
        initialPrice: "Initial Price",
        finalPrice: "Final Price",
        calloutFee: "Call-out Fee",
        fixedPrice: "Fixed Price",
        priceOpen: "Open",
        labelStatus: "Status",
        priceBase: "base",
        currencySom: "som",

        // Financials
        prepaidBalance: "Balance",
        balanceBlocked: "Balance Blocked",
        initialDeposit: "Initial Deposit",
        threshold: "Threshold",
        finNetBalance: "Net Balance",
        finTotalEarned: "Total Earned",
        finCommissionPaid: "Commission Paid",
        finCommissionOwed: "Commission Owed",
        finJobsDone: "Jobs Done",
        finPaid: "Paid",
        finPending: "Pending",
        // Transaction types for history
        transactionTopUp: "Top Up",
        transactionAdjustment: "Adjustment",
        transactionRefund: "Refund",
        transactionWaiver: "Waiver",
        transactionCommission: "Commission",
        debt: "Debt",

        // Profile
        rating: "Rating",
        completed: "Completed",
        refused: "Refused",
        professionalInfo: "Professional Info",
        serviceArea: "Service Area",
        license: "License",
        experience: "Experience",
        years: "years",
        specializations: "Specializations",
        jobs: "jobs",

        // Periods
        periodAll: "All Time",
        periodMonth: "Month",
        periodWeek: "Week",
        periodToday: "Today",

        // Schedule
        schedule: "Schedule",
        preferredDate: "Preferred Date",
        preferredTime: "Preferred Time",
        dateToday: "Today",
        dateTomorrow: "Tomorrow",
        timeMorning: "Morning",
        timeAfternoon: "Afternoon",
        timeEvening: "Evening",

        // Pricing
        pricing: "Pricing",
        pricingMasterQuotes: "Master Quotes",
        pricingFixed: "Fixed Price",

        // Modals
        modalCompleteTitle: "Complete Job",
        modalFinalPrice: "Final Price",
        modalWorkPerformed: "Work Performed",
        modalHoursWorked: "Hours Worked",
        modalCancelTitle: "Refuse Job",
        modalSelectReason: "Select Reason",
        modalAdditionalNotes: "Additional Notes",
        modalOrderPrefix: "Order #",
        modalPaymentTitle: "Confirm Payment",
        modalSelectMaster: "Select Master",
        modalAssignTitle: "Assign Master",
        modalAssignMsg: "Assign {0} to this order?",

        // Payment
        paymentAmount: "Amount",
        paymentProof: "Proof URL",
        paymentMethod: "Payment Method",
        paymentCash: "Cash",
        paymentTransfer: "Transfer",
        paymentCard: "Card",

        // Badges
        badgeDispute: "Dispute",
        badgeUnpaid: "Unpaid",
        badgeStuck: "Stuck",

        // Issues
        issueAllIssues: "All Issues",
        issueStuck: "Stuck",
        issueDisputed: "Disputed",
        issueUnpaid: "Unpaid",
        issueCanceled: "Canceled",

        // Time Units
        timeUnitNow: "Just now",
        timeUnitMins: "m ago",
        timeUnitHours: "h ago",
        timeUnitDays: "d ago",

        // Toasts & Alerts
        toastCopied: "Copied!",
        toastUpdated: "Updated",
        toastPaymentConfirmed: "Payment confirmed!",
        toastMasterAssigned: "Master assigned!",
        toastOrderCreated: "Order created!",
        toastFillRequired: "Please fill required fields",
        toastClientNameRequired: "Client name is required",
        toastFixPhone: "Fix phone format",
        toastConfirmDetails: "Please confirm details",
        toastSelectPaymentMethod: "Select payment method",
        toastProofRequired: "Proof required for transfers",
        toastNoOrderSelected: "No order selected",
        toastFormCleared: "Form cleared",
        toastAssignFail: "Assignment failed",
        toastCreateFailed: "Create failed",
        toastMasterUnassigned: "Master removed",
        toastFailedPrefix: "Failed: ",
        alertLogoutTitle: "Logout",
        alertLogoutMsg: "Are you sure?",
        alertLogoutBtn: "Logout",
        alertCancelTitle: "Cancel Order",
        alertCancelMsg: "Are you sure?",
        alertAssignBtn: "Assign",
        alertUnassignTitle: "Remove Master",
        alertUnassignMsg: "Remove master and reopen this order?",
        alertUnassignBtn: "Remove",

        // Errors
        errorPhoneFormat: "Invalid format (+996...)",
        errorAssignInvalidStatus: "Order is not available for assignment",
        errorAssignMasterNotVerified: "Master is not verified",
        errorAssignMasterInactive: "Master is inactive",
        errorAssignMasterNotFound: "Master not found",
        errorAssignOrderNotFound: "Order not found",
        errorAssignUnauthorized: "Unauthorized to assign",
        errorMasterLimitReached: "Master has reached the active jobs limit",
        errorMasterDetailsUnavailable: "Master details unavailable",
        errorCannotUnassign: "Cannot remove master from completed/confirmed order",
        errorInitialBelowCallout: "Initial price cannot be lower than call-out fee",
        errorFinalBelowCallout: "Final price cannot be lower than call-out fee",
        errorGeneric: "Something went wrong",
        errorNetwork: "Network error",
        errorLoadFailed: "Failed to load data",

        // Create Order
        createOrder: "Create Order",
        createClientDetails: "Client Details",
        createPhone: "Phone",
        createName: "Name",
        createLocation: "Location",
        createDistrict: "District",
        createFullAddress: "Full Address",
        createServiceType: "Service Type",
        createProblemDesc: "Problem Description",
        createPrice: "Price",
        createInternalNote: "Internal Note",
        createConfirm: "Confirm Details",
        createClear: "Clear",
        createPublish: "Publish Order",
        createAnother: "Create Another",
        createSuccess: "Order Created!",
        createViewQueue: "View in Queue",
        createAnotherOrder: "Create Another Order",

        // Labels
        labelCallout: "Call-out:",
        labelInitial: "Initial:",
        labelFinal: "Final:",
        labelAmount: "Amount:",
        labelProof: "Proof URL",
        labelRating: "Rating",
        labelLimitReached: "Limit reached",
        labelJobs: "jobs",
        labelMasterPrefix: "Master: ",
        labelAllServices: "All Services",

        // Buttons
        btnEdit: "Edit",
        btnCancelEdit: "Cancel Edit",
        btnClose: "Close",
        btnPay: "Pay",
        btnCopy: "Copy",
        btnCall: "Call",
        btnDetails: "Details",
        btnSaveChanges: "Save Changes",
        btnPayWithAmount: "Pay {0}c",
        btnSortNewest: "↓ Newest",
        btnSortOldest: "↑ Oldest",

        // Recent & Other
        recentBtn: "Recent",
        needsAttention: "Needs Attention",
        needsAttentionSort: "Sort",
        noMasters: "No available masters",
        msgNoMatch: "No items match filter",
        emptyList: "No orders found",
        ordersQueue: "Orders Queue",
        showFilters: "Show Filters",
        hideFilters: "Hide Filters",
        selectOption: "Select Option",
        keepLocation: "Keep Location",
        startFresh: "Start Fresh",

        // Misc Placeholders
        districtPlaceholder: "e.g. Leninsky",
        addressPlaceholder: "Full Address",

        // Empty States
        emptyPoolTitle: "No available orders",
        emptyJobsTitle: "No active jobs",
        noOrderHistory: "No order history",

        // Drawer
        drawerTitle: "Order #{0}",
        // Dispatcher (Queue)
        dispatcherPro: "Dispatcher Pro",
        startToSeeAddress: "Start to see address",
        stuck: "Stuck",
        unassigned: "Unassigned",
        sortNewest: "Newest",
        sortOldest: "Oldest",
        titlePayment: "Confirm Payment",
        titleSelectMaster: "Select Master",
        titleMasterDetails: "Master Details",
        fixedAmount: "Fixed Amount",
        problemDesc: "Problem Description",
        toastPasted: "Pasted & formatted",
        toastClipboardEmpty: "Clipboard empty",
        toastPasteFailed: "Paste failed - check permissions",
        toastOrderFailed: "Order creation failed",
        alertAssignTitle: "Assign Master",
        alertAssignMsg: "Assign {0} to this order?",
        placeholderSearch: "Search...",
        pickerStatus: "Status",
        pickerDispatcher: "Dispatcher",
        pickerUrgency: "Urgency",
        pickerService: "Service",
        pickerSort: "Sort",
        pickerErrorType: "Error Type",
        badgeCanceled: "Canceled",
        debtPrefix: "Debt: ",
        filterStatusPlaced: "Placed",
        filterStatusReopened: "Reopened",
        filterStatusClaimed: "Claimed",
        filterStatusStarted: "Started",
        filterStatusCompleted: "Completed (Unpaid)",
        filterStatusConfirmed: "Confirmed",
        filterStatusPayment: "Awaiting Payment",
        filterStatusDisputed: "Disputed",
        filterStatusCanceled: "Canceled",
        filterStatusExpired: "Expired",
        // Dispatcher (Extra)
        createOrientir: "Landmark/Orientir",
        orientirPlaceholder: "e.g. Near Beta Stores",
        labelOrientir: "Landmark:",
        labelCountryside: "Outskirts",

        // Analytics
        analytics: "Analytics",
        analyticsTitle: "Analytics",
        analyticsOverview: "Overview",
        analyticsOperations: "Operations",
        analyticsFinancial: "Financial",
        analyticsQuality: "Quality",
        analyticsPeople: "People",
        analyticsSubtitle: "Top-level performance and risk signals. Tap any card for details.",
        analyticsTimeRange: "Time Range",
        analyticsLast7d: "Last 7 days",
        analyticsDailyOrders: "Daily Orders",
        analyticsDailyGMV: "Daily Gross Merchandise Value (GMV)",
        analyticsDailyCommission: "Daily Commission",
        analyticsOrdersVsRevenue: "Orders vs revenue",
        analyticsStatusMix: "Status Mix",
        analyticsOrderFunnel: "Order Funnel",
        analyticsTopAreas: "Top Areas",
        analyticsTopServices: "Top Services",
        analyticsUrgencyMix: "Urgency Mix",
        analyticsCancelReasons: "Cancellation Reasons",
        analyticsBacklog: "Backlog Orders",
        analyticsFunnel: "Order Funnel",
        analyticsOpenOrders: "Open",
        analyticsActiveJobs: "Active Jobs",
        analyticsCompleted: "Completed",
        analyticsCanceled: "Canceled",
        analyticsTotalOrders: "Total Orders",
        analyticsCompletionRate: "completion rate",
        analyticsCancelRate: "cancel rate",
        analyticsOpenBacklog: "Open Backlog",
        analyticsOlder24h: "older than 24h",
        analyticsGMVFull: "Gross Merchandise Value (GMV)",
        analyticsAvgOrderValue: "Average Order Value (AOV)",
        analyticsAverageRating: "Average Rating",
        analyticsUrgentShare: "urgent share",
        analyticsAvgAge: "Average Age",
        analyticsServiceLevelRisk: "Service Level Risk",
        analyticsOver48h: "open > 48h",
        analyticsCommissionCollectedFull: "Commission Collected",
        analyticsOutstandingCommission: "Outstanding Commission",
        analyticsTotalBalances: "Total Balances",
        analyticsLowBalance: "low balance",
        analyticsCommissionRate: "Commission Rate",
        analyticsPlatformRate: "Platform rate",
        analyticsGMVvsCommission: "Gross Merchandise Value vs Commission",
        analyticsCommissionSplit: "Commission Split",
        analyticsTopByCompleted: "Top by Completed Jobs",
        analyticsTopByRevenue: "Top by Revenue",
        analyticsTopByRating: "Top by Rating",
        analyticsJobs: "jobs",
        currency: "som",
        // Analytics granularity
        analyticsViewBy: "View by",
        analyticsGranularityHour: "Hours",
        analyticsGranularityDay: "Days",
        analyticsGranularityWeek: "Weeks",
        analyticsGranularityMonth: "Months",
        analyticsGranularityQuarter: "Quarters",
        analyticsGranularityYear: "Years",
    },
    ru: {
        // General
        welcome: "Добро пожаловать",
        loading: "Загрузка...",
        cancel: "Отмена",
        save: "Сохранить",
        clear: "Очистить",
        confirm: "Подтвердить",
        close: "Закрыть",
        back: "Назад",
        next: "Далее",
        ok: "OK",
        yes: "Да",
        no: "Нет",
        search: "Поиск...",
        noResults: "Ничего не найдено",
        retry: "Повторить",
        refresh: "Обновить",

        // Auth & User
        verified: "Подтвержден",
        unverified: "Не подтвержден",
        online: "В сети",
        offline: "Не в сети",
        logout: "Выход",
        logoutConfirm: "Вы уверены, что хотите выйти?",

        logoutConfirm: "Вы уверены, что хотите выйти?",

        // Login
        loginTitle: "Вход для партнеров",
        loginEmail: "Эл. почта",
        loginEmailPlaceholder: "email@example.com",
        loginPassword: "Пароль",
        loginPasswordPlaceholder: "********",
        loginButton: "Войти",
        loginSupport: "Поддержка",
        loginFooter: "(c) 2024 Master.kg",
        loginErrorMissing: "Введите email и пароль",
        loginErrorGeneric: "Произошла непредвиденная ошибка",
        loginErrorInvalidCredentials: "Неверный email или пароль",
        loginSuccess: "Вход выполнен!",
        // Tabs & Navigation
        tabOrders: "Заказы",
        tabMyAccount: "Мой аккаунт",
        tabCreate: "Создать",
        tabQueue: "Очередь",
        tabOverview: "Обзор",
        tabPeople: "Люди",
        tabSettings: "Настройки",

        // Dashboard Sections
        sectionAvailable: "Доступные заказы",
        sectionMyJobs: "Мои работы",
        sectionEarnings: "Доходы",
        sectionHistory: "История",
        sectionProfile: "Профиль",
        sectionSettings: "Настройки",
        sectionClient: "Клиент",
        sectionMaster: "Мастер",
        sectionDetails: "Детали заказа",
        sectionFinancials: "Финансы",
        sectionNote: "Внутренняя заметка",

        // Settings (Master)
        settingsLanguage: "Язык",
        settingsTheme: "Тема",
        settingsThemeHint: "Настройте внешний вид",
        settingsSupport: "Поддержка",
        settingsSupportPhone: "Позвонить",
        settingsSupportWhatsApp: "WhatsApp",
        settingsSupportTelegram: "Telegram",

        // Filters
        filterUrgency: "Срочность",
        filterService: "Услуга",
        filterArea: "Район",
        filterAll: "Все",
        filterClear: "Сброс",
        filterStatus: "Статус",
        filterSort: "Сортировка",
        filterNewestFirst: "Сначала новые",
        filterOldestFirst: "Сначала старые",
        filterAllOrders: "Все заказы",
        filterMyOrders: "Мои заказы",
        filterAllUrgency: "Любая срочность",
        hideFilters: "Скрыть фильтры",
        showFilters: "Показать фильтры",

        // Admin
        adminTitle: "Админ Про",
        peopleMasters: "Мастера",
        peopleDispatchers: "Диспетчеры",
        settingsTitle: "Настройки Платформы",
        basePayout: "Базовая плата за выезд",
        commissionRate: "Ставка Комиссии",
        priceDeviation: "Отклонение Цены",
        autoClaimTimeout: "Таймаут Авто-Принятия",
        orderExpiry: "Срок Заказа",
        serviceTypes: "Типы Услуг",
        addType: "Добавить Тип",
        revenueTrend: "Тренд Выручки",
        commissionCollection: "Сбор Комиссии",
        // Admin Settings Extended
        configurationTitle: "Конфигурация",
        configurationSubtitle: "Общие настройки и параметры платформы",
        serviceTypesTitle: "Типы услуг",
        serviceTypesSubtitle: "Управление доступными категориями услуг",
        addServiceType: "Добавить тип услуги",
        editServiceType: "Редактировать тип услуги",
        createService: "Создать услугу",
        updateService: "Обновить услугу",
        noServiceTypes: "Типы услуг не настроены",
        addFirstService: "Добавьте первый тип услуги",
        codeReadOnly: "Только чтение",
        codeUnique: "Код (Уникальный ID)",
        localizedNames: "Локализованные названия",
        englishName: "Английское название",
        russianName: "Русское название",
        kyrgyzName: "Кыргызское название",
        editSettings: "Изменить настройки",
        standardCallout: "Используется, если выезд не задан",
        platformCommission: "Процент комиссии платформы",
        thresholdAlerts: "Порог для оповещений о цене",
        minutesExpire: "Минуты до истечения заказа",
        hoursExpire: "Часы до истечения невостребованных заказов",
        // People Management
        addMaster: "Добавить мастера",
        addDispatcher: "Добавить диспетчера",
        noMastersFound: "Мастера не найдены",
        noDispatchersFound: "Диспетчеры не найдены",
        topUp: "ПОПОЛНИТЬ",
        verify: "ВЕРИФИЦИРОВАТЬ",
        unverify: "ОТМЕНИТЬ ВЕРИФИКАЦИЮ",
        activate: "АКТИВИРОВАТЬ",
        deactivate: "ДЕАКТИВИРОВАТЬ",
        active: "Активен",
        inactive: "Неактивен",
        // Create Order Page
        createNewOrder: "Создать новый заказ",
        clientPhoneRequired: "Телефон клиента *",
        districtRequired: "Район *",
        fullAddressRequired: "Полный адрес *",
        problemRequired: "Описание проблемы *",
        describeIssue: "Опишите проблему...",
        confirmDetails: "Подтвердить данные",
        // Details Drawer
        orderDetails: "Детали заказа",
        client: "КЛИЕНТ",
        addressSection: "АДРЕС",
        problemSection: "ПРОБЛЕМА",
        editDetails: "Редактировать",
        saveChanges: "Сохранить изменения",
        reopenOrder: "Переоткрыть заказ",
        forceAssignMaster: "Назначить мастера",
        reassignMaster: "Переназначить мастера",
        removeMaster: "Снять мастера",
        confirmUnassignTitle: "Снять мастера",
        confirmUnassignMsg: "Снять мастера и вернуть заказ в пул?",
        paymentProofVerification: "ВЕРИФИКАЦИЯ ОПЛАТЫ",
        badgePaymentProof: "Чек оплаты",
        approve: "Одобрить",
        reject: "Отклонить",
        processing: "Обработка...",
        selectMasterAssign: "Выберите мастера для назначения:",
        noAvailableMasters: "Нет доступных мастеров",
        // Modals
        recordCommissionPayment: "Записать оплату комиссии",
        master: "Мастер",
        amountSom: "Сумма (сом)",
        confirmPayment: "Подтвердить оплату",
        saving: "Сохранение...",
        settingsSaved: "Настройки сохранены",
        errorSavingSettings: "Ошибка сохранения настроек",
        // Balance
        balanceTopUp: "Пополнение баланса",
        addBalance: "Добавить баланс",
        searchOrders: "Поиск заказов...",
        exit: "Выход",
        // Overview Stats
        totalOrders: "Всего заказов",
        activeJobs: "Активные работы",
        pending: "В ожидании",
        confirmed: "Подтверждено",
        totalBalances: "Общий баланс",
        lowBalance: "Низкий баланс",
        below500: "Ниже 500 сом",
        mastersCount: "мастеров",
        revenueTrendTitle: "Тренд выручки",
        selectedPeriod: "Выбранный период",
        ordersByService: "Заказы по услугам",
        // Sidebar Navigation
        overview: "Обзор",
        orders: "Заказы",
        people: "Люди",
        settings: "Настройки",
        // Person Details Drawer
        contactInfo: "КОНТАКТНАЯ ИНФОРМАЦИЯ",
        edit: "Изменить",
        fullName: "Полное имя",
        phone: "Телефон",
        email: "Эл. почта",
        experienceYears: "Опыт (лет)",
        financials: "ФИНАНСЫ",
        balance: "Баланс:",
        performance: "ПОКАЗАТЕЛИ",
        completedJobs: "Выполнено работ:",
        viewOrderHistory: "История заказов",
        topUpBalance: "Пополнить баланс",
        unverifyMaster: "Отменить верификацию",
        verifyMaster: "Верифицировать мастера",
        resetPassword: "Сбросить пароль",
        stats: "СТАТИСТИКА",
        status: "Статус:",
        created: "Создан:",
        // Balance Modal
        addMasterBalance: "Добавить баланс мастера",
        notesOptional: "Примечания (необязательно)",
        // Status Badges
        verified: "ВЕРИФИЦИРОВАН",
        unverified: "НЕ ВЕРИФИЦИРОВАН",
        // Date Filter
        filterAll: "Все",
        filterToday: "Сегодня",
        filterWeek: "Неделя",
        filterMonth: "Месяц",
        filterCustom: "Другое",
        startDate: "Начало:",
        endDate: "Конец:",
        selectDate: "Выбрать дату",
        // Service Type Sidebar
        modifyExistingService: "Редактировать существующую услугу",
        createNewCategory: "Создать новую категорию услуг",
        code: "Код:",
        // Reset Password Modal
        resetPasswordWarning: "Это действие немедленно изменит пароль пользователя. Для входа ему потребуется новый пароль.",
        newPassword: "Новый пароль *",
        confirmPasswordLabel: "Подтвердите пароль *",
        minCharacters: "Минимум 6 символов",
        reenterPassword: "Повторите пароль",
        passwordsNotMatch: "Пароли не совпадают",
        resetting: "Сброс...",
        // Add User Modal
        createNewMasterAccount: "Создать аккаунт мастера",
        createNewDispatcherAccount: "Создать аккаунт диспетчера",
        emailRequired: "Эл. почта *",
        passwordRequired: "Пароль *",
        fullNameRequired: "Полное имя *",
        phoneOptional: "Телефон",
        serviceAreaOptional: "Зона обслуживания",
        experienceOptional: "Опыт (лет)",
        creating: "Создание...",
        createMaster: "Создать мастера",
        createDispatcher: "Создать диспетчера",
        // Order Time Labels
        justNow: "Только что",
        minsAgo: "мин назад",
        hoursAgo: "ч назад",
        daysAgo: "д назад",
        tapViewDetails: "Нажмите для просмотра",
        // Show Filters
        showFilters: "Показать фильтры",
        hideFilters: "Скрыть фильтры",
        needsAttention: "Требует внимания",
        // Dashboard Charts
        ordersByService: "Заказы по услугам",
        orderStatus: "Статус заказов",
        commissionCollection: "Сбор комиссии",
        allTime: "Всё время",
        collected: "Собрано",
        outstanding: "Ожидается",
        chartNew: "Нов.",
        chartClaimed: "Заяв.",
        chartWIP: "Раб.",
        chartDone: "Гот.",
        chartPaid: "Опл.",
        chartCanceled: "Отм.",

        // Service Types
        servicePlumbing: "Сантехника",
        serviceElectrician: "Электрик",
        serviceCleaning: "Уборка",
        serviceCarpenter: "Плотник",
        serviceRepair: "Ремонт",
        serviceInstallation: "Установка",
        serviceMaintenance: "Обслуживание",
        serviceOther: "Другое",
        serviceApplianceRepair: "Ремонт техники",
        serviceBuilding: "Строительство",
        serviceInspection: "Осмотр",
        serviceHvac: "Кондиционеры",
        servicePainting: "Покраска",
        serviceFlooring: "Полы",
        serviceRoofing: "Кровля",
        serviceLandscaping: "Ландшафт",

        // Urgency
        urgencyEmergency: "Аварийный",
        urgencyUrgent: "Срочный",
        urgencyPlanned: "Плановый",

        // Status
        statusPlaced: "Размещен",
        statusClaimed: "Принят",
        statusStarted: "Начат",
        statusCompleted: "Завершен",
        statusConfirmed: "Подтвержден",
        statusCanceled: "Отменен",
        statusCanceledByMaster: "Отменен мастером",
        statusCanceledByClient: "Отменен клиентом",
        statusReopened: "Переоткрыт",
        statusExpired: "Истек",
        statusActive: "Активные",
        statusPayment: "Ожидает оплаты",
        statusDisputed: "Спорные",
        statusAll: "Все заказы",

        // Actions
        actionClaim: "Взять",
        actionLocked: "Заблокировано",
        actionStart: "Начать",
        actionCancel: "Отказаться",
        actionComplete: "Завершить",
        actionBack: "Назад",
        actionSubmit: "Отправить",
        actionEdit: "Изменить",
        actionSave: "Сохранить",
        actionDelete: "Удалить",
        actionAssign: "Назначить",
        actionUnassign: "Снять мастера",
        actionReopen: "Переоткрыть",
        actionPay: "Оплатить",
        actionCall: "Звонок",
        actionCopy: "Копия",
        actionCopyAddress: "Копировать адрес",
        actionCopyPhone: "Копировать телефон",
        actionClose: "Закрыть",
        actionCopyAddress: "Копировать адрес",
        actionCopyPhone: "Копировать телефон",

        // Cards
        cardStartToSeeAddress: "Начните, чтобы увидеть адрес",
        cardPendingApproval: "Ожидает подтверждения",
        cardUnassigned: "Не назначен",
        cardStuck: "Застрял",
        activeOrderTitle: "Активный заказ",

        // Order Details
        clientName: "Имя клиента",
        clientPhone: "Телефон клиента",
        address: "Адрес",
        fullAddress: "Полный адрес",
        district: "Район",
        description: "Описание",
        problemDescription: "Описание проблемы",
        serviceType: "Тип услуги",
        price: "Цена",
        initialPrice: "Начальная цена",
        finalPrice: "Итоговая цена",
        calloutFee: "Плата за выезд",
        fixedPrice: "Фикс. цена",
        priceOpen: "Открыто",
        labelStatus: "Статус",
        priceBase: "фикс",
        currencySom: "сом",

        // Financials
        prepaidBalance: "Баланс",
        balanceBlocked: "Баланс заблокирован",
        initialDeposit: "Начальный депозит",
        threshold: "Порог",
        finNetBalance: "Чистый баланс",
        finTotalEarned: "Всего заработано",
        finCommissionPaid: "Комиссия оплачена",
        finCommissionOwed: "Комиссия к оплате",
        finJobsDone: "Выполнено работ",
        finPaid: "Оплачено",
        finPending: "Ожидает",
        // Transaction types for history
        transactionTopUp: "Пополнение",
        transactionAdjustment: "Корректировка",
        transactionRefund: "Возврат",
        transactionWaiver: "Списание",
        transactionCommission: "Комиссия",
        debt: "Долг",

        // Profile
        rating: "Рейтинг",
        completed: "Завершено",
        refused: "Отказов",
        professionalInfo: "Проф. информация",
        serviceArea: "Район обслуживания",
        license: "Лицензия",
        experience: "Опыт",
        years: "лет",
        specializations: "Специализации",
        jobs: "заказов",

        // Periods
        periodAll: "Все время",
        periodMonth: "Месяц",
        periodWeek: "Неделя",
        periodToday: "Сегодня",

        // Schedule
        schedule: "Расписание",
        preferredDate: "Желаемая дата",
        preferredTime: "Желаемое время",
        dateToday: "Сегодня",
        dateTomorrow: "Завтра",
        timeMorning: "Утро",
        timeAfternoon: "День",
        timeEvening: "Вечер",

        // Pricing
        pricing: "Цена",
        pricingMasterQuotes: "Оценка мастера",
        pricingFixed: "Фикс. цена",

        // Modals
        modalCompleteTitle: "Завершение работы",
        modalFinalPrice: "Итоговая цена",
        modalWorkPerformed: "Выполненные работы",
        modalHoursWorked: "Затрачено часов",
        modalCancelTitle: "Отказ от работы",
        modalSelectReason: "Выберите причину",
        modalAdditionalNotes: "Дополнительные заметки",
        modalOrderPrefix: "Заказ #",
        modalPaymentTitle: "Подтвердить оплату",
        modalSelectMaster: "Выберите мастера",
        modalAssignTitle: "Назначить мастера",
        modalAssignMsg: "Назначить {0} на этот заказ?",

        // Payment
        paymentAmount: "Сумма",
        paymentProof: "Ссылка на чек",
        paymentMethod: "Способ оплаты",
        paymentCash: "Наличные",
        paymentTransfer: "Перевод",
        paymentCard: "Карта",

        // Badges
        badgeDispute: "Спор",
        badgeUnpaid: "Не оплачен",
        badgeStuck: "Застрял",

        // Issues
        issueAllIssues: "Все вопросы",
        issueStuck: "Застрял",
        issueDisputed: "Спорный",
        issueUnpaid: "Не оплачен",
        issueCanceled: "Отменен",

        // Time Units
        timeUnitNow: "Только что",
        timeUnitMins: " м назад",
        timeUnitHours: " ч назад",
        timeUnitDays: " д назад",

        // Toasts & Alerts
        toastCopied: "Скопировано!",
        toastUpdated: "Обновлено",
        toastPaymentConfirmed: "Оплата подтверждена!",
        toastMasterAssigned: "Мастер назначен!",
        toastOrderCreated: "Заказ создан!",
        toastFillRequired: "Заполните обязательные поля",
        toastClientNameRequired: "Имя клиента обязательно",
        toastFixPhone: "Исправьте формат телефона",
        toastConfirmDetails: "Подтвердите детали",
        toastSelectPaymentMethod: "Выберите способ оплаты",
        toastProofRequired: "Нужен чек перевода",
        toastNoOrderSelected: "Заказ не выбран",
        toastFormCleared: "Форма очищена",
        toastAssignFail: "Ошибка назначения",
        toastCreateFailed: "Ошибка создания",
        toastMasterUnassigned: "Мастер снят",
        toastFailedPrefix: "Ошибка: ",
        alertLogoutTitle: "Выход",
        alertLogoutMsg: "Вы уверены?",
        alertLogoutBtn: "Выход",
        alertCancelTitle: "Отменить заказ",
        alertCancelMsg: "Вы уверены?",
        alertAssignBtn: "Назначить",
        alertUnassignTitle: "Снять мастера",
        alertUnassignMsg: "Снять мастера и вернуть заказ в пул?",
        alertUnassignBtn: "Снять",

        // Errors
        errorPhoneFormat: "Неверный формат (+996...)",
        errorAssignInvalidStatus: "Заказ недоступен для назначения",
        errorAssignMasterNotVerified: "Мастер не подтвержден",
        errorAssignMasterInactive: "Мастер неактивен",
        errorAssignMasterNotFound: "Мастер не найден",
        errorAssignOrderNotFound: "Заказ не найден",
        errorAssignUnauthorized: "Нет прав на назначение",
        errorMasterLimitReached: "Мастер достиг лимита активных заказов",
        errorMasterDetailsUnavailable: "Детали мастера недоступны",
        errorCannotUnassign: "Нельзя снять мастера с подтвержденного/завершенного заказа",
        errorInitialBelowCallout: "Начальная цена не может быть ниже платы за выезд",
        errorFinalBelowCallout: "Итоговая цена не может быть ниже платы за выезд",
        errorGeneric: "Что-то пошло не так",
        errorNetwork: "Ошибка сети",
        errorLoadFailed: "Не удалось загрузить данные",

        // Create Order
        createOrder: "Создать заказ",
        createClientDetails: "Данные клиента",
        createPhone: "Телефон",
        createName: "Имя",
        createLocation: "Локация",
        createDistrict: "Район",
        createFullAddress: "Полный адрес",
        createServiceType: "Тип услуги",
        createProblemDesc: "Описание проблемы",
        createPrice: "Цена",
        createInternalNote: "Внутренняя заметка",
        createConfirm: "Подтвердить детали",
        createClear: "Очистить",
        createPublish: "Опубликовать",
        createAnother: "Создать еще",
        createSuccess: "Заказ создан!",
        createViewQueue: "Посмотреть в очереди",
        createAnotherOrder: "Создать еще заказ",

        // Labels
        labelCallout: "Выезд:",
        labelInitial: "Начальная:",
        labelFinal: "Итоговая:",
        labelAmount: "Сумма:",
        labelProof: "Ссылка на чек",
        labelRating: "Рейтинг",
        labelLimitReached: "Лимит достигнут",
        labelJobs: "заказов",
        labelMasterPrefix: "Мастер: ",
        labelAllServices: "Все услуги",

        // Buttons
        btnEdit: "Изменить",
        btnCancelEdit: "Отмена",
        btnClose: "Закрыть",
        btnPay: "Оплатить",
        btnCopy: "Копия",
        btnCall: "Звонок",
        btnDetails: "Детали",
        btnSaveChanges: "Сохранить",
        btnPayWithAmount: "Оплатить {0}c",
        btnSortNewest: "↓ Новые",
        btnSortOldest: "↑ Старые",

        // Recent & Other
        recentBtn: "Недавние",
        needsAttention: "Требует внимания",
        needsAttentionSort: "Сорт.",
        noMasters: "Нет доступных мастеров",
        msgNoMatch: "Нет результатов",
        emptyList: "Заказов не найдено",
        ordersQueue: "Очередь заказов",
        showFilters: "Показать фильтры",
        hideFilters: "Скрыть фильтры",
        selectOption: "Выберите",
        keepLocation: "Оставить адрес",
        startFresh: "Начать заново",

        // Misc Placeholders
        districtPlaceholder: "напр. Ленинский",
        addressPlaceholder: "Полный адрес",

        // Empty States
        emptyPoolTitle: "Нет доступных заказов",
        emptyJobsTitle: "Нет активных работ",
        noOrderHistory: "История заказов пуста",

        // Drawer
        drawerTitle: "Заказ #{0}",
        // Dispatcher (Queue)
        dispatcherPro: "Диспетчер Pro",
        startToSeeAddress: "Начните, чтобы увидеть адрес",
        stuck: "Завис",
        unassigned: "Не назначен",
        sortNewest: "Новые",
        sortOldest: "Старые",
        titlePayment: "Подтвердить оплату",
        titleSelectMaster: "Выбрать мастера",
        titleMasterDetails: "Детали мастера",
        fixedAmount: "Фикс. сумма",
        problemDesc: "Описание проблемы",
        toastPasted: "Вставлено и отформатировано",
        toastClipboardEmpty: "Буфер обмена пуст",
        toastPasteFailed: "Не удалось вставить — проверьте доступ",
        toastOrderFailed: "Ошибка создания заказа",
        alertAssignTitle: "Назначить мастера",
        alertAssignMsg: "Назначить {0} на этот заказ?",
        placeholderSearch: "Поиск...",
        pickerStatus: "Статус",
        pickerDispatcher: "Диспетчер",
        pickerUrgency: "Срочность",
        pickerService: "Услуга",
        pickerSort: "Сортировка",
        pickerErrorType: "Тип ошибки",
        badgeCanceled: "Отменен",
        debtPrefix: "Долг: ",
        filterStatusPlaced: "Размещен",
        filterStatusReopened: "Переоткрыт",
        filterStatusClaimed: "Принят",
        filterStatusStarted: "Начат",
        filterStatusCompleted: "Завершен (не оплачен)",
        filterStatusConfirmed: "Подтвержден",
        filterStatusPayment: "Ожидает оплаты",
        filterStatusDisputed: "Спорный",
        filterStatusCanceled: "Отменен",
        filterStatusExpired: "Истек",
        // Dispatcher (Extra)
        createOrientir: "Ориентир",
        orientirPlaceholder: "например, рядом с Бета Маркетом",
        labelOrientir: "Ориентир:",
        labelCountryside: "Окраина",

        // Analytics
        analytics: "Аналитика",
        analyticsTitle: "Аналитика",
        analyticsOverview: "Обзор",
        analyticsOperations: "Операции",
        analyticsFinancial: "Финансы",
        analyticsQuality: "Качество",
        analyticsPeople: "Сотрудники",
        analyticsSubtitle: "Ключевые метрики и риски. Нажмите на карточку для деталей.",
        analyticsTimeRange: "Период",
        analyticsLast7d: "Последние 7 дней",
        analyticsDailyOrders: "Ежедневные заказы",
        analyticsDailyGMV: "Ежедневная валовая выручка (GMV)",
        analyticsDailyCommission: "Ежедневная комиссия",

        analyticsOrdersVsRevenue: "Заказы vs выручка",
        analyticsStatusMix: "Статусы",
        analyticsOrderFunnel: "Воронка заказов",
        analyticsTopAreas: "Топ районов",
        analyticsTopServices: "Топ услуг",
        analyticsUrgencyMix: "Срочность",
        analyticsCancelReasons: "Причины отмены",
        analyticsBacklog: "Невыполненные заказы",
        analyticsFunnel: "Воронка заказов",
        analyticsOpenOrders: "Открытые",
        analyticsActiveJobs: "Активные работы",
        analyticsCompleted: "Завершено",
        analyticsCanceled: "Отменено",
        analyticsTotalOrders: "Всего заказов",
        analyticsCompletionRate: "доля завершения",
        analyticsCancelRate: "доля отмен",
        analyticsOpenBacklog: "Открытые заказы",
        analyticsOlder24h: "старше 24ч",
        analyticsGMVFull: "Валовый оборот (GMV)",
        analyticsAvgOrderValue: "Средний чек (AOV)",
        analyticsAverageRating: "Средний рейтинг",
        analyticsUrgentShare: "доля срочных",
        analyticsAvgAge: "Средний возраст",
        analyticsServiceLevelRisk: "Риск сервиса",
        analyticsOver48h: "открыто > 48ч",
        analyticsCommissionCollectedFull: "Собранная комиссия",
        analyticsOutstandingCommission: "Комиссия к сбору",
        analyticsTotalBalances: "Сумма балансов",
        analyticsLowBalance: "низкий баланс",
        analyticsCommissionRate: "Комиссия платформы",
        analyticsPlatformRate: "Ставка платформы",
        analyticsGMVvsCommission: "GMV vs комиссия",
        analyticsCommissionSplit: "Разбивка комиссии",
        analyticsTopByCompleted: "Топ по завершенным",
        analyticsTopByRevenue: "Топ по выручке",
        analyticsTopByRating: "Топ по рейтингу",
        analyticsJobs: "заказов",
        currency: "сом",
        // Analytics granularity
        analyticsViewBy: "Смотреть по",
        analyticsGranularityHour: "Часы",
        analyticsGranularityDay: "Дни",
        analyticsGranularityWeek: "Недели",
        analyticsGranularityMonth: "Месяцы",
        analyticsGranularityQuarter: "Кварталы",
        analyticsGranularityYear: "Годы",
    },
    kg: {
        // General
        welcome: "Кош келиңиз",
        loading: "Жүктөлүүдө...",
        cancel: "Жокко чыгаруу",
        save: "Сактоо",
        clear: "Тазалоо",
        confirm: "Ырастоо",
        close: "Жабуу",
        back: "Артка",
        next: "Кийинки",
        ok: "OK",
        yes: "Ооба",
        no: "Жок",
        search: "Издөө...",
        noResults: "Эч нерсе табылган жок",
        retry: "Кайталоо",
        refresh: "Жаңылоо",

        // Auth & User
        verified: "Текшерилген",
        unverified: "Текшерилбеген",
        online: "Онлайн",
        offline: "Офлайн",
        logout: "Чыгуу",
        logoutConfirm: "Чыгууну каалайсызбы?",

        // Login
        loginTitle: "Өнөктөштөр үчүн кирүү",
        loginEmail: "Э-почта",
        loginEmailPlaceholder: "email@example.com",
        loginPassword: "Купуя сөз",
        loginPasswordPlaceholder: "********",
        loginButton: "Кирүү",
        loginSupport: "Колдоо",
        loginFooter: "(c) 2024 Master.kg",
        loginErrorMissing: "Э-почта жана купуя сөздү жазыңыз",
        loginErrorGeneric: "Күтүлбөгөн ката кетти",
        loginSuccess: "Ийгиликтүү кирдиңиз!",
        // Tabs & Navigation
        tabOrders: "Буйрутмалар",
        tabMyAccount: "Менин аккаунтум",
        tabCreate: "Жаңы түзүү",
        tabQueue: "Кезек",
        tabOverview: "Сереп",
        tabPeople: "Адамдар",
        tabSettings: "Жөндөөлөр",

        // Dashboard Sections
        sectionAvailable: "Жеткиликтүү буйрутмалар",
        sectionMyJobs: "Менин иштерим",
        sectionEarnings: "Кирешелер",
        sectionHistory: "Тарых",
        sectionProfile: "Профиль",
        sectionSettings: "Орнотуулар",
        sectionClient: "Кардар",
        sectionMaster: "Уста",
        sectionDetails: "Буйрутма чоо-жайы",
        sectionFinancials: "Финансы",
        sectionNote: "Ички белги",

        // Settings (Master)
        settingsLanguage: "Тил",
        settingsTheme: "Тема",
        settingsThemeHint: "Көрүнүшүн тууралаңыз",
        settingsSupport: "Колдоо",
        settingsSupportPhone: "Чалуу",
        settingsSupportWhatsApp: "WhatsApp",
        settingsSupportTelegram: "Telegram",

        // Filters
        filterUrgency: "Шашылыш",
        filterService: "Кызмат",
        filterArea: "Район",
        filterAll: "Бардыгы",
        filterClear: "Тазалоо",
        filterStatus: "Статус",
        filterSort: "Реттөө",
        filterNewestFirst: "Жаңылар биринчи",
        filterOldestFirst: "Эскилер биринчи",
        filterAllOrders: "Бардык буйрутмалар",
        filterMyOrders: "Менин буйрутмаларым",
        filterAllUrgency: "Бардык шашылыштык",
        hideFilters: "Фильтрлөрдү жашыруу",
        showFilters: "Фильтрлөрдү көрсөтүү",

        // Admin
        adminTitle: "Админ Про",
        peopleMasters: "Усталар",
        peopleDispatchers: "Диспетчерлер",
        settingsTitle: "Платформа Жөндөөлөрү",
        basePayout: "Негизги чыгуу акысы",
        commissionRate: "Комиссия",
        priceDeviation: "Баанын Өзгөрүшү",
        autoClaimTimeout: "Авто-Алуу Убактысы",
        orderExpiry: "Буйрутма Мөөнөтү",
        serviceTypes: "Кызмат Түрлөрү",
        addType: "Түр Кошуу",
        revenueTrend: "Киреше Тренди",
        commissionCollection: "Комиссия Чогултуу",
        // Admin Settings Extended
        configurationTitle: "Конфигурация",
        configurationSubtitle: "Платформанын жалпы жөндөөлөрү",
        serviceTypesTitle: "Кызмат түрлөрү",
        serviceTypesSubtitle: "Жеткиликтүү кызмат категорияларын башкаруу",
        addServiceType: "Кызмат түрүн кошуу",
        editServiceType: "Кызмат түрүн өзгөртүү",
        createService: "Кызмат түзүү",
        updateService: "Кызматты жаңылоо",
        noServiceTypes: "Кызмат түрлөрү жок",
        addFirstService: "Биринчи кызмат түрүн кошуңуз",
        codeReadOnly: "Окуу үчүн гана",
        codeUnique: "Код (Уникалдуу ID)",
        localizedNames: "Локализацияланган аталыштар",
        englishName: "Англисче аталыш",
        russianName: "Орусча аталыш",
        kyrgyzName: "Кыргызча аталыш",
        editSettings: "Жөндөөлөрдү өзгөртүү",
        standardCallout: "Чыгуу акысы жок болсо колдонулат",
        platformCommission: "Платформанын комиссия пайызы",
        thresholdAlerts: "Баа эскертүүлөрү үчүн чек",
        minutesExpire: "Буйрутманын бүтүшүнө чейинки мүнөттөр",
        hoursExpire: "Талап кылынбаган буйрутмалардын бүтүшүнө чейинки сааттар",
        // People Management
        addMaster: "Уста кошуу",
        addDispatcher: "Диспетчер кошуу",
        noMastersFound: "Усталар табылган жок",
        noDispatchersFound: "Диспетчерлер табылган жок",
        topUp: "ТОЛУКТОО",
        verify: "ТЕКШЕРҮҮ",
        unverify: "ТЕКШЕРҮҮНҮ ЖОККО ЧЫГАРУУ",
        activate: "АКТИВДЕШТИРҮҮ",
        deactivate: "ӨЧҮРҮҮ",
        active: "Активдүү",
        inactive: "Активдүү эмес",
        // Create Order Page
        createNewOrder: "Жаңы буйрутма түзүү",
        clientPhoneRequired: "Кардардын телефону *",
        districtRequired: "Район *",
        fullAddressRequired: "Толук дарек *",
        problemRequired: "Көйгөй сүрөттөмөсү *",
        describeIssue: "Көйгөйдү сүрөттөп бериңиз...",
        confirmDetails: "Маалыматтарды ырастоо",
        // Details Drawer
        orderDetails: "Буйрутманын чоо-жайы",
        client: "КАРДАР",
        addressSection: "ДАРЕК",
        problemSection: "КӨЙГӨЙ",
        editDetails: "Өзгөртүү",
        saveChanges: "Өзгөртүүлөрдү сактоо",
        reopenOrder: "Буйрутманы кайра ачуу",
        forceAssignMaster: "Устаны дайындоо",
        reassignMaster: "Reassign Master",
        removeMaster: "Remove Master",
        confirmUnassignTitle: "Remove Master",
        confirmUnassignMsg: "Remove the assigned master and reopen this order?",
        paymentProofVerification: "ТӨЛӨМ ТЕКШЕРҮҮ",
        badgePaymentProof: "Payment Proof",
        approve: "Макулдоо",
        reject: "Четке кагуу",
        processing: "Иштетүү...",
        selectMasterAssign: "Дайындоо үчүн устаны тандаңыз:",
        noAvailableMasters: "No available masters found",
        // Modals
        recordCommissionPayment: "Комиссия төлөмүн жазуу",
        master: "Уста",
        amountSom: "Сумма (сом)",
        confirmPayment: "Төлөмдү ырастоо",
        saving: "Сакталууда...",
        settingsSaved: "Жөндөөлөр сакталды",
        errorSavingSettings: "Жөндөөлөрдү сактоо катасы",
        // Balance
        balanceTopUp: "Баланс толуктоо",
        addBalance: "Баланс кошуу",
        searchOrders: "Буйрутмаларды издөө...",
        exit: "Чыгуу",
        // Overview Stats
        totalOrders: "Бардык буйрутмалар",
        activeJobs: "Активдүү жумуштар",
        pending: "Күтүүдө",
        confirmed: "Тастыкталган",
        totalBalances: "Жалпы баланс",
        lowBalance: "Төмөн баланс",
        below500: "500 сомдон төмөн",
        mastersCount: "усталар",
        revenueTrendTitle: "Киреше тренди",
        selectedPeriod: "Тандалган мезгил",
        ordersByService: "Кызматтар боюнча буйрутмалар",
        // Dashboard Charts
        orderStatus: "Буйрутма статусу",
        commissionCollection: "Комиссия чогултуу",
        allTime: "Бардык убакыт",
        collected: "Чогулган",
        outstanding: "Күтүлүүдө",
        chartNew: "Жаңы",
        chartClaimed: "Алын.",
        chartWIP: "Ишт.",
        chartDone: "Бүт.",
        chartPaid: "Төл.",
        chartCanceled: "Алм.",
        // Sidebar Navigation
        overview: "Сереп",
        orders: "Буйрутмалар",
        people: "Адамдар",
        settings: "Жөндөөлөр",
        // Person Details Drawer
        contactInfo: "БАЙЛАНЫШ МААЛЫМАТЫ",
        edit: "Өзгөртүү",
        fullName: "Толук аты",
        phone: "Телефон",
        email: "Эл. почта",
        experienceYears: "Тажрыйба (жыл)",
        financials: "ФИНАНСЫ",
        balance: "Баланс:",
        performance: "КӨРСӨТКҮЧТӨР",
        completedJobs: "Аткарылган иштер:",
        viewOrderHistory: "Буйрутма тарыхы",
        topUpBalance: "Балансты толтуруу",
        unverifyMaster: "Текшерүүнү жокко чыгаруу",
        verifyMaster: "Устаны текшерүү",
        resetPassword: "Сырсөздү калыбына келтирүү",
        stats: "СТАТИСТИКА",
        status: "Статус:",
        created: "Түзүлгөн:",
        // Balance Modal
        addMasterBalance: "Уста балансын кошуу",
        notesOptional: "Эскертүүлөр (милдеттүү эмес)",
        // Status Badges
        verified: "ТЕКШЕРИЛГЕН",
        unverified: "ТЕКШЕРИЛБЕГЕН",
        // Date Filter
        filterAll: "Баары",
        filterToday: "Бүгүн",
        filterWeek: "Апта",
        filterMonth: "Ай",
        filterCustom: "Башка",
        startDate: "Башталыш:",
        endDate: "Аякталыш:",
        selectDate: "Күндү тандоо",
        // Service Type Sidebar
        modifyExistingService: "Бар кызматты өзгөртүү",
        createNewCategory: "Жаңы кызмат категориясын түзүү",
        code: "Код:",
        // Reset Password Modal
        resetPasswordWarning: "Бул аракет колдонуучунун сырсөзүн дароо өзгөртөт. Кирүү үчүн аларга жаңы сырсөз керек болот.",
        newPassword: "Жаңы сырсөз *",
        confirmPasswordLabel: "Сырсөздү ырастаңыз *",
        minCharacters: "Минимум 6 символ",
        reenterPassword: "Сырсөздү кайра жазыңыз",
        passwordsNotMatch: "Сырсөздөр дал келген жок",
        resetting: "Калыбына келтирүү...",
        // Add User Modal
        createNewMasterAccount: "Уста аккаунтун түзүү",
        createNewDispatcherAccount: "Диспетчер аккаунтун түзүү",
        emailRequired: "Эл. почта *",
        passwordRequired: "Сырсөз *",
        fullNameRequired: "Толук аты *",
        phoneOptional: "Телефон",
        serviceAreaOptional: "Кызмат аймагы",
        experienceOptional: "Тажрыйба (жыл)",
        creating: "Түзүлүүдө...",
        createMaster: "Устаны түзүү",
        createDispatcher: "Диспетчерди түзүү",
        // Order Time Labels
        justNow: "Азыр эле",
        minsAgo: "мүн мурун",
        hoursAgo: "саат мурун",
        daysAgo: "күн мурун",
        tapViewDetails: "Көрүү үчүн басыңыз",
        // Show Filters
        showFilters: "Фильтрлерди көрсөтүү",
        hideFilters: "Фильтрлерди жашыруу",
        needsAttention: "Көңүл буруңуз",

        // Service Types
        servicePlumbing: "Сантехника",
        serviceElectrician: "Электрик",
        serviceCleaning: "Тазалоо",
        serviceCarpenter: "Уста",
        serviceRepair: "Оңдоо",
        serviceInstallation: "Орнотуу",
        serviceMaintenance: "Тейлөө",
        serviceOther: "Башка",
        serviceApplianceRepair: "Техника оңдоо",
        serviceBuilding: "Курулуш",
        serviceInspection: "Текшерүү",
        serviceHvac: "Кондиционер",
        servicePainting: "Боёк",
        serviceFlooring: "Пол",
        serviceRoofing: "Чатыр",
        serviceLandscaping: "Ландшафт",

        // Urgency
        urgencyEmergency: "Авариялык",
        urgencyUrgent: "Шашылыш",
        urgencyPlanned: "Пландалган",

        // Status
        statusPlaced: "Жайгаштырылды",
        statusClaimed: "Кабыл алынды",
        statusStarted: "Башталды",
        statusCompleted: "Аяктады",
        statusConfirmed: "Тастыкталды",
        statusCanceled: "Жокко чыгарылды",
        statusCanceledByMaster: "Уста жокко чыгарды",
        statusCanceledByClient: "Клиент жокко чыгарды",
        statusReopened: "Кайра ачылган",
        statusExpired: "Мөөнөтү бүткөн",
        statusActive: "Активдүү",
        statusPayment: "Төлөм күтүүдө",
        statusDisputed: "Талаштуу",
        statusAll: "Баардык буйрутмалар",

        // Actions
        actionClaim: "Алуу",
        actionLocked: "Кулпуланган",
        actionStart: "Баштоо",
        actionCancel: "Баш тартуу",
        actionComplete: "Аяктоо",
        actionBack: "Артка",
        actionSubmit: "Жиберүү",
        actionEdit: "Өзгөртүү",
        actionSave: "Сактоо",
        actionDelete: "Өчүрүү",
        actionAssign: "Дайындоо",
        actionUnassign: "Устаны алуу",
        actionReopen: "Кайра ачуу",
        actionPay: "Төлөө",
        actionCall: "Чалуу",
        actionCopy: "Көчүрүү",
        actionCopyAddress: "Даректи көчүрүү",
        actionCopyPhone: "Телефонду көчүрүү",
        actionClose: "Жабуу",
        actionCopyAddress: "Даректи көчүрүү",
        actionCopyPhone: "Телефонду көчүрүү",

        // Cards
        cardStartToSeeAddress: "Даректи көрүү үчүн баштаңыз",
        cardPendingApproval: "Тастыктоону күтүүдө",
        cardUnassigned: "Дайындала элек",
        cardStuck: "Токтоп калды",
        activeOrderTitle: "Активдүү заказ",

        // Order Details
        clientName: "Кардардын аты",
        clientPhone: "Кардардын телефону",
        address: "Дарек",
        fullAddress: "Толук дарек",
        district: "Район",
        description: "Сүрөттөмө",
        problemDescription: "Көйгөйдүн сүрөттөлүшү",
        serviceType: "Кызмат түрү",
        price: "Баасы",
        initialPrice: "Баштапкы баа",
        finalPrice: "Акыркы баа",
        calloutFee: "Чыгуу акысы",
        fixedPrice: "Белгиленген баа",
        priceOpen: "Ачык",
        labelStatus: "Абалы",
        priceBase: "негиз",
        currencySom: "сом",

        // Financials
        prepaidBalance: "Баланс",
        balanceBlocked: "Баланс бөгөттөлдү",
        initialDeposit: "Баштапкы депозит",
        threshold: "Чеги",
        finNetBalance: "Таза баланс",
        finTotalEarned: "Бардык киреше",
        finCommissionPaid: "Төлөнгөн комиссия",
        finCommissionOwed: "Төлөнчү комиссия",
        finJobsDone: "Аткарылган иштер",
        finPaid: "Төлөндү",
        finPending: "Күтүүдө",
        // Transaction types for history
        transactionTopUp: "Толуктоо",
        transactionAdjustment: "Оңдоо",
        transactionRefund: "Кайтаруу",
        transactionWaiver: "Кечүү",
        transactionCommission: "Комиссия",
        debt: "Карыз",

        // Profile
        rating: "Рейтинг",
        completed: "Аяктаган",
        refused: "Баш тарткан",
        professionalInfo: "Кесиптик маалымат",
        serviceArea: "Кызмат көрсөтүү аймагы",
        license: "Лицензия",
        experience: "Тажрыйба",
        years: "жыл",
        specializations: "Адистиктер",
        jobs: "иштер",

        // Periods
        periodAll: "Бардык убакыт",
        periodMonth: "Ай",
        periodWeek: "Апта",
        periodToday: "Бүгүн",

        // Schedule
        schedule: "Убакыт",
        preferredDate: "Каалаган дата",
        preferredTime: "Каалаган убакыт",
        dateToday: "Бүгүн",
        dateTomorrow: "Эртең",
        timeMorning: "Эртең менен",
        timeAfternoon: "Түш",
        timeEvening: "Кечинде",

        // Pricing
        pricing: "Баа",
        pricingMasterQuotes: "Мастер баа",
        pricingFixed: "Белгиленген",

        // Modals
        modalCompleteTitle: "Ишти аяктоо",
        modalFinalPrice: "Акыркы баа",
        modalWorkPerformed: "Аткарылган жумуштар",
        modalHoursWorked: "Иштелген сааттар",
        modalCancelTitle: "Иштен баш тартуу",
        modalSelectReason: "Себебин тандаңыз",
        modalAdditionalNotes: "Кошумча белгилер",
        modalOrderPrefix: "Буйрутма #",
        modalPaymentTitle: "Төлөмдү ырастоо",
        modalSelectMaster: "Уста тандаңыз",
        modalAssignTitle: "Устаны дайындоо",
        modalAssignMsg: "{0} деген устаны бул буйрутмага дайындайсызбы?",

        // Payment
        paymentAmount: "Сумма",
        paymentProof: "Чектин шилтемеси",
        paymentMethod: "Төлөм ыкмасы",
        paymentCash: "Накталай",
        paymentTransfer: "Которуу",
        paymentCard: "Карта",

        // Badges
        badgeDispute: "Талаш",
        badgeUnpaid: "Төлөнбөгөн",
        badgeStuck: "Токтогон",

        // Issues
        issueAllIssues: "Бардык маселелер",
        issueStuck: "Токтогон",
        issueDisputed: "Талаштуу",
        issueUnpaid: "Төлөнбөгөн",
        issueCanceled: "Жокко чыгарылган",

        // Time Units
        timeUnitNow: "Азыр эле",
        timeUnitMins: "м мурун",
        timeUnitHours: "с мурун",
        timeUnitDays: "к мурун",

        // Toasts & Alerts
        toastCopied: "Көчүрүлдү!",
        toastUpdated: "Жаңыланды",
        toastPaymentConfirmed: "Төлөм ырасталды!",
        toastMasterAssigned: "Мастер дайындалды!",
        toastOrderCreated: "Буйрутма түзүлдү!",
        toastFillRequired: "Талап кылынган талааларды толтуруңуз",
        toastClientNameRequired: "Кардардын аты талап кылынат",
        toastFixPhone: "Телефон форматын оңдоңуз",
        toastConfirmDetails: "Маалыматтарды ырастаңыз",
        toastSelectPaymentMethod: "Төлөм ыкмасын тандаңыз",
        toastProofRequired: "Чек талап кылынат",
        toastNoOrderSelected: "Буйрутма тандалган жок",
        toastFormCleared: "Форма тазаланды",
        toastAssignFail: "Дайындоо катасы",
        toastCreateFailed: "Түзүү катасы",
        toastMasterUnassigned: "Мастер алынды",
        toastFailedPrefix: "Ката: ",
        alertLogoutTitle: "Чыгуу",
        alertLogoutMsg: "Ишенимдүүсүзбү?",
        alertLogoutBtn: "Чыгуу",
        alertCancelTitle: "Буйрутманы жокко чыгаруу",
        alertCancelMsg: "Ишенимдүүсүзбү?",
        alertAssignBtn: "Дайындоо",
        alertUnassignTitle: "Устаны алуу",
        alertUnassignMsg: "Устаны алып, буйрутманы кайра пулга кайтарасызбы?",
        alertUnassignBtn: "Алуу",

        // Errors
        errorPhoneFormat: "Ката формат (+996...)",
        errorAssignInvalidStatus: "Буйрутма дайындоого жеткиликсиз",
        errorAssignMasterNotVerified: "Уста тастыкталган эмес",
        errorAssignMasterInactive: "Уста активдүү эмес",
        errorAssignMasterNotFound: "Уста табылган жок",
        errorAssignOrderNotFound: "Буйрутма табылган жок",
        errorAssignUnauthorized: "Дайындоого уруксат жок",
        errorMasterLimitReached: "Устанын активдүү буйрутма чеги толду",
        errorMasterDetailsUnavailable: "Уста маалыматы жеткиликсиз",
        errorCannotUnassign: "Тастыкталган/аяктаган буйрутмадан устаны ала албайсыз",
        errorInitialBelowCallout: "Баштапкы баа чыгуу акысынан төмөн боло албайт",
        errorFinalBelowCallout: "Акыркы баа чыгуу акысынан төмөн боло албайт",
        errorGeneric: "Бир нерсе туура эмес болду",
        errorNetwork: "Тармак катасы",
        loginErrorGeneric: "Бир нерсе туура эмес болду",
        loginErrorInvalidCredentials: "Эл. почта же сырсөз туура эмес",
        loginSuccess: "Кирүү ийгиликтүү!",
        errorLoadFailed: "Маалыматты жүктөө ишке ашкан жок",

        // Create Order
        createOrder: "Буйрутма түзүү",
        createClientDetails: "Кардардын маалыматы",
        createPhone: "Телефон",
        createName: "Аты",
        createLocation: "Жайгашкан жер",
        createDistrict: "Район",
        createFullAddress: "Толук дарек",
        createServiceType: "Кызмат түрү",
        createProblemDesc: "Көйгөйдүн сүрөттөлүшү",
        createPrice: "Баасы",
        createInternalNote: "Ички белги",
        createConfirm: "Толуктоолорду ырастоо",
        createClear: "Тазалоо",
        createPublish: "Жарыялоо",
        createAnother: "Дагы түзүү",
        createSuccess: "Буйрутма түзүлдү!",
        createViewQueue: "Кезекти көрүү",
        createAnotherOrder: "Дагы буйрутма түзүү",

        // Labels
        labelCallout: "Чакыруу:",
        labelInitial: "Баштапкы:",
        labelFinal: "Акыркы:",
        labelAmount: "Сумма:",
        labelProof: "Чектин шилтемеси",
        labelRating: "Рейтинг",
        labelLimitReached: "Чек толду",
        labelJobs: "иштер",
        labelMasterPrefix: "Уста: ",
        labelAllServices: "Бардык кызматтар",

        // Buttons
        btnEdit: "Өзгөртүү",
        btnCancelEdit: "Жокко чыгаруу",
        btnClose: "Жабуу",
        btnPay: "Төлөө",
        btnCopy: "Көчүрүү",
        btnCall: "Чалуу",
        btnDetails: "Деталдар",
        btnSaveChanges: "Сактоо",
        btnPayWithAmount: "{0}с төлөө",
        btnSortNewest: "↓ Жаңылар",
        btnSortOldest: "↑ Эскилер",

        // Recent & Other
        recentBtn: "Акыркы",
        needsAttention: "Көңүл буруңуз",
        needsAttentionSort: "Реттөө",
        noMasters: "Бош уста жок",
        msgNoMatch: "Эч нерсе табылган жок",
        emptyList: "Буйрутма табылган жок",
        ordersQueue: "Буйрутмалар кезеги",
        showFilters: "Фильтрлерди көрсөтүү",
        hideFilters: "Фильтрлерди жашыруу",
        selectOption: "Тандоо",
        keepLocation: "Даректи сактоо",
        startFresh: "Жаңыдан баштоо",

        // Misc Placeholders
        districtPlaceholder: "мис. Ленин",
        addressPlaceholder: "Толук дарек",

        // Empty States
        emptyPoolTitle: "Жеткиликтүү буйрутмалар жок",
        emptyJobsTitle: "Активдүү жумуштар жок",
        noOrderHistory: "Буйрутма тарыхы бош",

        // Drawer
        drawerTitle: "Буйрутма #{0}",
        // Dispatcher (Queue)
        dispatcherPro: "Диспетчер Pro",
        startToSeeAddress: "Даректи көрүү үчүн баштаңыз",
        stuck: "Токтоп калган",
        unassigned: "Дайындалган эмес",
        sortNewest: "Жаңы",
        sortOldest: "Эски",
        titlePayment: "Төлөмдү ырастоо",
        titleSelectMaster: "Устаны тандоо",
        titleMasterDetails: "Устанын маалыматы",
        fixedAmount: "Бекитилген сумма",
        problemDesc: "Көйгөйдүн сүрөттөлүшү",
        toastPasted: "Коюлуп, форматталды",
        toastClipboardEmpty: "Буфер бош",
        toastPasteFailed: "Коюу ишке ашкан жок — уруксатты текшериңиз",
        toastOrderFailed: "Буйрутма түзүү катасы",
        alertAssignTitle: "Устаны дайындоо",
        alertAssignMsg: "{0} ушул буйрутмага дайындалсынбы?",
        placeholderSearch: "Издөө...",
        pickerStatus: "Статус",
        pickerDispatcher: "Диспетчер",
        pickerUrgency: "Шашылыштык",
        pickerService: "Кызмат",
        pickerSort: "Иреттөө",
        pickerErrorType: "Ката түрү",
        badgeCanceled: "Жокко чыгарылган",
        debtPrefix: "Карыз: ",
        filterStatusPlaced: "Жайгаштырылган",
        filterStatusReopened: "Кайра ачылган",
        filterStatusClaimed: "Кабыл алынган",
        filterStatusStarted: "Башталган",
        filterStatusCompleted: "Аяктаган (төлөнгөн эмес)",
        filterStatusConfirmed: "Тастыкталды",
        filterStatusPayment: "Төлөм күтүлүүдө",
        filterStatusDisputed: "Талаштуу",
        filterStatusCanceled: "Жокко чыгарылган",
        filterStatusExpired: "Мөөнөтү бүткөн",
        // Dispatcher (Extra)
        createOrientir: "Ориентир",
        orientirPlaceholder: "мисалы, Бета Маркеттин жанында",
        labelOrientir: "Ориентир:",
        labelCountryside: "Шаар четинде",

        // Analytics
        analytics: "Аналитика",
        analyticsTitle: "Аналитика",
        analyticsOverview: "Обзор",
        analyticsOperations: "Операциялар",
        analyticsFinancial: "Финансы",
        analyticsQuality: "Сапат",
        analyticsPeople: "Кызматкерлер",
        analyticsSubtitle: "Негизги көрсөткүчтөр жана тобокелдиктер. Карточканы басып деталдарын көрүңүз.",
        analyticsTimeRange: "Мөөнөт",
        analyticsLast7d: "Акыркы 7 күн",
        analyticsDailyOrders: "Күнүмдүк буйрутмалар",
        analyticsDailyGMV: "Күнүмдүк валовый киреше (GMV)",
        analyticsDailyCommission: "Күнүмдүк комиссия",

        analyticsOrdersVsRevenue: "Заказдар vs киреше",
        analyticsStatusMix: "Статустар",
        analyticsOrderFunnel: "Заказдардын воронкасы",
        analyticsTopAreas: "Топ аймактар",
        analyticsTopServices: "Топ кызматтар",
        analyticsUrgencyMix: "Шашылыштык",
        analyticsCancelReasons: "Жокко чыгаруу себептери",
        analyticsBacklog: "Аякталбаган заказдар",
        analyticsFunnel: "Заказдардын воронкасы",
        analyticsOpenOrders: "Ачык",
        analyticsActiveJobs: "Активдүү иштер",
        analyticsCompleted: "Аяктады",
        analyticsCanceled: "Жокко чыгарылды",
        analyticsTotalOrders: "Бардык заказдар",
        analyticsCompletionRate: "аяктоо үлүшү",
        analyticsCancelRate: "жокко чыгаруу үлүшү",
        analyticsOpenBacklog: "Ачык заказдар",
        analyticsOlder24h: "24 сааттан ашкан",
        analyticsGMVFull: "Жалпы товар жүгүртүү (GMV)",
        analyticsAvgOrderValue: "Орточо чек (AOV)",
        analyticsAverageRating: "Орточо рейтинг",
        analyticsUrgentShare: "шашылыш үлүшү",
        analyticsAvgAge: "Орточо жашы",
        analyticsServiceLevelRisk: "Кызмат тобокели",
        analyticsOver48h: "48 сааттан ашык",
        analyticsCommissionCollectedFull: "Жыйналган комиссия",
        analyticsOutstandingCommission: "Жыйнала элек комиссия",
        analyticsTotalBalances: "Баланс суммасы",
        analyticsLowBalance: "төмөн баланс",
        analyticsCommissionRate: "Платформанын комиссиясы",
        analyticsPlatformRate: "Платформа ставкасы",
        analyticsGMVvsCommission: "GMV vs комиссия",
        analyticsCommissionSplit: "Комиссия бөлүштүрүү",
        analyticsTopByCompleted: "Көп бүткөндөр",
        analyticsTopByRevenue: "Көп киреше алып келгендер",
        analyticsTopByRating: "Жогорку рейтинг",
        analyticsJobs: "жумуш",
        currency: "сом",
        // Analytics granularity
        analyticsViewBy: "Көрүү",
        analyticsGranularityHour: "Сааттар",
        analyticsGranularityDay: "Күндөр",
        analyticsGranularityWeek: "Апталар",
        analyticsGranularityMonth: "Айлар",
        analyticsGranularityQuarter: "Чейректер",
        analyticsGranularityYear: "Жылдар",
    }
};

const LocalizationContext = createContext();

export const LocalizationProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    useEffect(() => {
        loadLanguage();
    }, []);

    const loadLanguage = async () => {
        try {
            const storedLang = await AsyncStorage.getItem('user-language');
            if (storedLang) {
                setLanguage(storedLang);
            }
        } catch (e) {
            console.error('Failed to load language', e);
        }
    };

    const changeLanguage = async (lang) => {
        try {
            await AsyncStorage.setItem('user-language', lang);
            setLanguage(lang);
        } catch (e) {
            console.error('Failed to save language', e);
        }
    };

    const cycleLanguage = async () => {
        const langs = ['en', 'ru', 'kg'];
        const nextIndex = (langs.indexOf(language) + 1) % langs.length;
        await changeLanguage(langs[nextIndex]);
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['en']?.[key] || key;
    };

    return (
        <LocalizationContext.Provider value={{ language, setLanguage: changeLanguage, cycleLanguage, t, translations }}>
            {children}
        </LocalizationContext.Provider>
    );
};

export const useLocalization = () => useContext(LocalizationContext);

