import { Dimensions, Platform, StyleSheet } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const styles = StyleSheet.create({
    container: { flex: 1 },
    loadingContainer: {
        flex: 1,
        backgroundColor: '#0b1120',
        justifyContent: 'center',
        alignItems: 'center',
    },
    mainContent: {
        flex: 1,
        padding: 24,
        backgroundColor: '#0b1120',
    },
    scrollContent: {
        flex: 1,
    },
    // Tab Buttons (People toggle)
    tabBtn: {
        paddingVertical: 8,
        paddingHorizontal: 16,
    },
    tabBtnActive: {
        backgroundColor: '#3b82f6',
    },
    tabBtnLight: {
        backgroundColor: 'transparent',
    },
    tabBtnText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#94a3b8',
    },
    tabBtnTextActive: {
        color: '#fff',
        fontWeight: '600',
    },
    listViewContainer: {
        flex: 1,
        paddingHorizontal: 8,
    },

    // Headers
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    pageTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#ffffff',
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#1e293b',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#334155',
    },
    profileBadge: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#334155',
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileText: {
        color: '#fff',
        fontWeight: '600',
    },

    // Stats
    statsGrid: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 24,
        flexWrap: 'wrap',
    },

    // Charts
    chartsRow: {
        flexDirection: 'row',
        marginBottom: 24,
        gap: 16,
        flexWrap: 'wrap',
    },
    chartCard: {
        backgroundColor: '#1e293b',
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: '#334155',
    },
    chartTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#fff',
    },
    chartSubtitle: {
        fontSize: 12,
        color: '#94a3b8',
        marginBottom: 16,
        textTransform: 'uppercase',
    },

    // List Items
    filterSection: {
        marginBottom: 20,
    },
    listItemCard: {
        backgroundColor: '#1e293b',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#334155',
        marginBottom: 8,
    },
    peopleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
        flexWrap: 'nowrap',
    },
    peopleLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        flex: 1,
        minWidth: 0,
    },
    peopleInfo: { flex: 1, minWidth: 0 },
    peopleRight: {
        minWidth: 0,
        width: 'auto',
        maxWidth: '100%',
        alignItems: 'flex-end',
        justifyContent: 'center',
        flexShrink: 0,
        marginLeft: 12,
    },
    peopleInlineControls: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        gap: 8,
        flexWrap: 'nowrap',
        width: 'auto',
        maxWidth: '100%',
    },
    peopleBadge: {
        alignSelf: 'flex-end',
        maxWidth: '100%',
        marginBottom: 6,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        borderWidth: 1,
        alignItems: 'center',
    },
    peopleBadgeText: { fontSize: 9, fontWeight: '700', textAlign: 'center', lineHeight: 12, flexShrink: 1 },
    peopleActions: {
        flexDirection: 'row',
        justifyContent: SCREEN_WIDTH < 720 ? 'flex-start' : 'flex-end',
        gap: 6,
        rowGap: 6,
        flexWrap: 'wrap',
        alignSelf: 'stretch',
        marginTop: 6,
        width: '100%',
    },
    peopleActionsInline: {
        marginTop: 0,
        width: 'auto',
        alignSelf: 'auto',
        flexWrap: 'nowrap',
        justifyContent: 'flex-end',
    },
    peopleActionBtn: {
        minWidth: 64,
        width: undefined,
        flexGrow: 0,
        flexShrink: 1,
        maxWidth: 110,
    },
    peopleActionText: {
        fontSize: 10,
        fontWeight: '700',
        textAlign: 'center',
    },
    peopleMetaRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
        marginTop: 6,
    },
    peopleMetaChip: {
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderWidth: 1,
        borderColor: 'rgba(71,85,105,0.5)',
        backgroundColor: 'rgba(71,85,105,0.25)',
    },
    peopleMetaChipLight: {
        borderColor: '#cbd5e1',
        backgroundColor: '#f1f5f9',
    },
    peopleMetaChipText: {
        fontSize: 8,
        fontWeight: '700',
        color: '#cbd5e1',
    },
    peopleMetaChipTextLight: {
        color: '#475569',
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    itemTitle: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
    },
    itemSubtitle: {
        color: '#94a3b8',
        fontSize: 12,
        marginTop: 2,
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 20,
        maxWidth: 120,
    },
    statusText: {
        color: '#fff',
        fontSize: 9,
        fontWeight: '700',
        textAlign: 'center',
    },
    avatarCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    actionButton: {
        marginTop: 12,
        backgroundColor: '#22c55e',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    actionButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
        lineHeight: 16,
    },

    // Modals
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.7)',
        ...Platform.select({
            web: {
                position: 'fixed',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                width: '100vw',
                height: '100vh',
                zIndex: 1000,
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
            },
            default: {
                ...StyleSheet.absoluteFillObject,
            }
        })
    },
    modalContent: {
        backgroundColor: '#1e293b',
        width: 400,
        maxWidth: '90%',
        borderRadius: 20,
        padding: 24,
        borderWidth: 1,
        borderColor: '#334155',
        ...Platform.select({
            web: {
                alignSelf: 'center',
                margin: 'auto',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
            }
        })
    },
    modalContentLight: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 20,
    },
    modalTitleLight: {
        color: '#0f172a',
    },
    modalSubtitle: { fontSize: 12, color: '#64748b', marginBottom: 12 },
    modalAmount: { fontSize: 20, color: '#22c55e', fontWeight: '700', marginBottom: 16 },
    paymentMethods: { flexDirection: 'row', gap: 8, marginBottom: 16 },
    paymentMethod: { flex: 1, paddingVertical: 12, borderRadius: 10, backgroundColor: 'rgba(71,85,105,0.4)', alignItems: 'center' },
    paymentMethodActive: { backgroundColor: '#3b82f6' },
    paymentMethodText: { fontSize: 13, fontWeight: '600', color: '#fff', textTransform: 'capitalize' },
    modalButtons: { flexDirection: 'row', gap: 12, marginTop: 16 },
    modalCancel: { flex: 1, paddingVertical: 14, borderRadius: 10, backgroundColor: 'rgba(71,85,105,0.4)', alignItems: 'center' },
    modalCancelText: { fontSize: 14, fontWeight: '500', color: '#fff' },
    modalConfirm: { flex: 1, paddingVertical: 14, borderRadius: 10, backgroundColor: '#22c55e', alignItems: 'center' },
    modalConfirmText: { fontSize: 14, fontWeight: '700', color: '#fff' },
    masterDetailsCard: { backgroundColor: '#1e293b', borderRadius: 20, padding: 24 },
    masterDetailsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    masterDetailsName: { fontSize: 16, fontWeight: '700', color: '#fff', marginBottom: 4 },
    masterDetailsSub: { fontSize: 12, color: '#94a3b8', marginBottom: 12 },
    masterDetailsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    masterDetailsLabel: { fontSize: 12, color: '#64748b' },
    masterDetailsValue: { fontSize: 12, fontWeight: '700', color: '#fff' },
    masterDetailsBlocked: { marginTop: 8, fontSize: 12, color: '#ef4444', fontWeight: '600' },
    masterDetailsSection: { marginTop: 16, paddingTop: 12, borderTopWidth: 1, borderTopColor: 'rgba(148,163,184,0.2)' },
    masterDetailsSectionTitle: { fontSize: 12, fontWeight: '700', color: '#e2e8f0', marginBottom: 8 },
    masterDetailsTxRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    masterDetailsTxLabel: { fontSize: 12, color: '#e2e8f0' },
    masterDetailsTxMeta: { fontSize: 10, color: '#94a3b8' },
    masterDetailsTxAmount: { fontSize: 12, fontWeight: '700', color: '#22c55e' },
    masterDetailsEmpty: { fontSize: 11, color: '#94a3b8' },
    input: {
        backgroundColor: '#0f172a',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#334155',
        color: '#fff',
        padding: 12,
        marginBottom: 16,
    },
    inputLight: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
        color: '#0f172a',
    },
    cancelBtn: {
        flex: 1,
        backgroundColor: '#334155',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    confirmBtn: {
        flex: 1,
        backgroundColor: '#3b82f6',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    // --- Ported Styles ---
    card: {
        backgroundColor: '#1e293b',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#334155',
        marginBottom: 12,
    },
    drawerOverlay: { flex: 1, flexDirection: 'row', justifyContent: 'flex-end' },
    drawerOverlayWeb: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, zIndex: 500 },
    drawerBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
    drawerBackdropHidden: { flex: 0, width: 0 },
    drawerContent: { width: SCREEN_WIDTH > 500 ? 400 : SCREEN_WIDTH * 0.85, maxWidth: '100%', backgroundColor: '#1e293b', height: '100%' },
    drawerContentLight: { backgroundColor: '#fff', borderLeftWidth: 1, borderLeftColor: '#e2e8f0' },
    drawerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(71,85,105,0.3)' },
    drawerHeaderLight: { borderBottomColor: '#f1f5f9' },
    drawerTitle: { fontSize: 16, fontWeight: '700', color: '#fff' },
    drawerDate: { fontSize: 11, color: '#64748b' },
    drawerActions: { flexDirection: 'row', gap: 12 },
    drawerActionText: { fontSize: 18, color: '#94a3b8' },
    drawerBody: { flex: 1, padding: 16 },
    drawerSections: { flex: 1 },
    drawerSection: { marginBottom: 16 },
    drawerStatusRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    drawerStatusBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
    drawerStatusText: { fontSize: 12, fontWeight: '700', color: '#fff', textTransform: 'uppercase' },
    drawerBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, backgroundColor: '#3b82f6' },
    drawerBtnText: { fontSize: 12, fontWeight: '700', color: '#fff' },
    drawerSectionTitle: { fontSize: 10, fontWeight: '700', color: '#64748b', textTransform: 'uppercase', marginBottom: 8 },
    drawerCard: { backgroundColor: 'rgba(71,85,105,0.3)', borderRadius: 10, padding: 12 },
    drawerCardLight: { backgroundColor: '#f8fafc', borderColor: '#e2e8f0', borderWidth: 1 },
    drawerCardTitle: { fontSize: 14, fontWeight: '700', color: '#fff', marginBottom: 4 },
    drawerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
    drawerRowText: { fontSize: 13, color: '#94a3b8', flex: 1 },
    drawerRowBtns: { flexDirection: 'row', gap: 8 },
    drawerDesc: { fontSize: 13, color: '#94a3b8', lineHeight: 20 },
    masterHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    masterDetailsBtn: { backgroundColor: 'rgba(59,130,246,0.2)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
    masterDetailsBtnText: { fontSize: 11, fontWeight: '700', color: '#3b82f6' },
    finRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    finLabel: { fontSize: 12, color: '#64748b' },
    finValue: { fontSize: 14, fontWeight: '700', color: '#fff' },
    drawerNote: { fontSize: 13, color: '#f59e0b', fontStyle: 'italic', backgroundColor: 'rgba(245,158,11,0.1)', padding: 10, borderRadius: 8 },
    drawerIconBtn: { paddingHorizontal: 8, paddingVertical: 4, backgroundColor: 'rgba(59,130,246,0.2)', borderRadius: 6 },
    drawerIconBtnText: { fontSize: 10, fontWeight: '600', color: '#3b82f6' },
    editSection: { marginBottom: 16 },
    saveEditBtn: { backgroundColor: '#3b82f6', paddingVertical: 14, borderRadius: 10, alignItems: 'center', marginTop: 12 },
    saveEditText: { fontSize: 14, fontWeight: '700', color: '#fff' },
    reopenBtn: { backgroundColor: '#3b82f6', paddingVertical: 12, borderRadius: 10, alignItems: 'center', marginTop: 8 },
    reopenText: { fontSize: 13, fontWeight: '600', color: '#fff' },
    orderCancelBtn: { backgroundColor: '#ef4444', paddingVertical: 12, borderRadius: 10, alignItems: 'center', marginTop: 8 },
    orderCancelText: { fontSize: 13, fontWeight: '600', color: '#fff' },
    transferBtn: { backgroundColor: '#0ea5e9', paddingVertical: 12, borderRadius: 10, alignItems: 'center', marginTop: 8 },
    transferText: { fontSize: 13, fontWeight: '600', color: '#fff' },
    forceAssignBtn: { backgroundColor: '#8b5cf6', paddingVertical: 12, borderRadius: 10, alignItems: 'center', marginTop: 8 },
    forceAssignText: { fontSize: 13, fontWeight: '600', color: '#fff' },
    editActionRow: { flexDirection: 'row', gap: 8, marginTop: 12 },
    editActionBtn: { flex: 1, paddingVertical: 10, borderRadius: 10, alignItems: 'center' },
    editActionPrimary: { backgroundColor: '#3b82f6' },
    editActionDanger: { backgroundColor: '#ef4444' },
    editActionSuccess: { backgroundColor: '#22c55e' },
    editActionText: { fontSize: 12, fontWeight: '700', color: '#fff' },
    editBtnActive: { backgroundColor: '#3b82f6', borderColor: '#3b82f6' },

    // Hamburger Sidebar Styles
    sidebarOverlay: { flex: 1, flexDirection: 'row' },
    sidebarContainer: { width: 280, height: '100%', backgroundColor: '#1e293b', borderRightWidth: 1, borderRightColor: 'rgba(71,85,105,0.3)' },
    sidebarHeader: { height: 64, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: 'rgba(71,85,105,0.3)' },
    sidebarBrand: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    sidebarBrandLogo: { width: 26, height: 26, borderRadius: 13 },
    sidebarTitle: { fontSize: 18, fontWeight: '700', color: '#fff' },
    sidebarClose: { padding: 8 },
    sidebarCloseText: { fontSize: 16, color: '#94a3b8' },
    sidebarNav: { flex: 1, paddingVertical: 20, paddingHorizontal: 16 },
    sidebarNavItem: { paddingVertical: 14, paddingHorizontal: 16, borderRadius: 12, marginBottom: 4 },
    sidebarNavItemActive: { backgroundColor: '#3b82f6' },
    sidebarNavIcon: { fontSize: 18, marginRight: 12, width: 24, textAlign: 'center' },
    sidebarNavText: { fontSize: 14, fontWeight: '600', color: '#94a3b8' },
    sidebarNavTextActive: { color: '#fff' },
    sidebarNavRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%' },
    sidebarBadge: { backgroundColor: '#ef4444', borderRadius: 10, paddingHorizontal: 6, paddingVertical: 2, marginLeft: 8 },
    sidebarBadgeText: { fontSize: 10, fontWeight: '700', color: '#fff' },
    createOrderBtn: { marginTop: 12, borderWidth: 1, borderColor: '#22c55e', borderStyle: 'dashed' },
    sidebarFooter: { padding: 16, borderTopWidth: 1, borderTopColor: 'rgba(71,85,105,0.3)' },
    sidebarUserCard: { flexDirection: 'row', alignItems: 'center', padding: 10, backgroundColor: 'rgba(71,85,105,0.3)', borderRadius: 12 },
    sidebarUserAvatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#3b82f6', justifyContent: 'center', alignItems: 'center' },
    sidebarUserAvatarText: { fontSize: 12, fontWeight: '700', color: '#fff' },
    sidebarUserInfo: { flex: 1, marginLeft: 10 },
    sidebarUserName: { fontSize: 13, fontWeight: '700', color: '#fff' },
    sidebarUserStatus: { fontSize: 10, color: '#22c55e' },
    sidebarLogoutBtn: { padding: 8 },
    sidebarLogoutText: { fontSize: 16, color: '#ef4444' },
    sidebarBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
    sidebarButtonRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
    sidebarSmallBtn: { flex: 1, height: 44, borderRadius: 10, backgroundColor: 'rgba(71,85,105,0.3)', justifyContent: 'center', alignItems: 'center' },
    sidebarThemeIcon: { fontSize: 20, color: '#94a3b8' },
    sidebarLangBtn: { flex: 1, height: 44, borderRadius: 10, backgroundColor: 'rgba(71,85,105,0.3)', justifyContent: 'center', alignItems: 'center' },
    sidebarLangText: { fontSize: 14, fontWeight: '700', color: '#fff' },

    // Header Styles
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(71,85,105,0.3)', marginBottom: 16 },
    headerLeft: { flexDirection: 'row', alignItems: 'center' },
    headerRight: { flexDirection: 'row', gap: 8 },
    headerTitle: { fontSize: 20, fontWeight: '700', color: '#fff' },
    menuBtn: { width: 44, height: 44, borderRadius: 12, backgroundColor: 'rgba(71,85,105,0.3)', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    menuBtnText: { fontSize: 22, color: '#94a3b8' },
    iconBtn: { width: 44, height: 44, borderRadius: 12, backgroundColor: 'rgba(71,85,105,0.3)', justifyContent: 'center', alignItems: 'center' },
    iconText: { fontSize: 20, color: '#94a3b8' },

    // Search Bar Styles
    searchRow: { flexDirection: 'row', gap: 8, marginBottom: 16 },
    searchInputWrapper: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(71,85,105,0.3)', borderRadius: 12, paddingHorizontal: 14 },
    searchIcon: { fontSize: 16, color: '#64748b', marginRight: 8 },
    searchIconText: { fontSize: 16, color: '#64748b', marginRight: 8 },
    searchInput: {
        flex: 1,
        paddingVertical: 12,
        color: '#fff',
        fontSize: 14,
        borderWidth: 0,
        ...(Platform.OS === 'web' ? { outlineStyle: 'none', outlineWidth: 0 } : {}),
    },
    searchClear: { padding: 4 },
    searchClearText: { fontSize: 14, color: '#64748b' },
    viewToggleBtn: { width: 48, borderRadius: 12, backgroundColor: 'rgba(71,85,105,0.3)', justifyContent: 'center', alignItems: 'center' },
    viewToggleBtnActive: { backgroundColor: '#3b82f6' },
    viewToggleBtnText: { fontSize: 20, color: '#94a3b8' },

    // Order Card Styles (Dispatcher-style)
    orderCard: { flex: 1, maxWidth: '48%', backgroundColor: 'rgba(30,41,59,0.9)', borderRadius: 12, padding: 14, marginBottom: 12, marginHorizontal: 4 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    cardService: { fontSize: 14, fontWeight: '700', color: '#fff', textTransform: 'capitalize' },
    cardStatus: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
    cardStatusText: { fontSize: 10, fontWeight: '700', color: '#fff', textTransform: 'uppercase' },
    cardAddr: { fontSize: 12, color: '#94a3b8', marginBottom: 8 },
    cardFooter: { flexDirection: 'row', justifyContent: 'space-between' },
    cardClient: { fontSize: 11, color: '#64748b' },
    cardTime: { fontSize: 10, color: '#64748b' },

    // Compact Row Styles
    compactRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(30,41,59,0.8)', borderRadius: 10, padding: 12, marginBottom: 8 },
    compactMain: { flex: 1, marginHorizontal: 12 },
    compactTopRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    compactId: { fontSize: 11, color: '#64748b', fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' },
    compactService: { fontSize: 14, fontWeight: '600', color: '#fff', textTransform: 'capitalize' },
    compactAddr: { fontSize: 12, color: '#94a3b8', marginTop: 2 },
    compactBottomRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 4 },
    compactClient: { fontSize: 12, color: '#64748b' },
    compactStatusBadge: { minWidth: 130, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
    compactStatusText: { fontSize: 9, fontWeight: '700', color: '#fff', textTransform: 'uppercase', textAlign: 'center' },
    compactRight: { flexDirection: 'row', alignItems: 'center' },
    compactTime: { fontSize: 11, color: '#64748b', marginRight: 8 },
    compactChevron: { fontSize: 18, color: '#64748b' },
    compactUrgency: { fontSize: 9, fontWeight: '700', color: '#f59e0b', backgroundColor: 'rgba(245,158,11,0.2)', paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3 },
    compactUrgencyEmergency: { color: '#ef4444', backgroundColor: 'rgba(239,68,68,0.2)' },
    compactMaster: { fontSize: 11, color: '#22c55e' },
    compactPrice: { fontSize: 11, fontWeight: '700', color: '#22c55e' },

    // Filter Styles (Dispatcher-style)
    filtersContainer: { marginBottom: 16 },
    filterControlsRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
    filterShowBtn: { paddingHorizontal: 14, height: 40, borderRadius: 12, backgroundColor: 'rgba(71,85,105,0.3)', justifyContent: 'center', alignItems: 'center' },
    filterShowBtnActive: { backgroundColor: '#3b82f6' },
    filterShowBtnText: { fontSize: 13, fontWeight: '600', color: '#94a3b8' },
    filterShowBtnTextActive: { color: '#fff' },

    filterDropdownRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    filterDropdown: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, height: 40, borderRadius: 12, backgroundColor: 'rgba(71,85,105,0.3)', borderWidth: 1, borderColor: 'rgba(71,85,105,0.5)' },
    filterDropdownText: { fontSize: 13, fontWeight: '600', color: '#fff', marginRight: 8 },
    filterDropdownArrow: { fontSize: 12, color: '#64748b' },

    // Clear Filters Button
    clearFiltersBtn: { paddingHorizontal: 14, height: 40, borderRadius: 12, backgroundColor: 'rgba(239,68,68,0.2)', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(239,68,68,0.3)' },
    clearFiltersBtnText: { fontSize: 13, fontWeight: '600', color: '#ef4444' },

    // Needs Attention Section Styles
    attentionContainer: { marginBottom: 16, backgroundColor: 'rgba(239,68,68,0.1)', borderRadius: 12, borderWidth: 1, borderColor: 'rgba(239,68,68,0.3)', padding: 12 },
    attentionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    attentionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    attentionTitle: { fontSize: 13, fontWeight: '700', color: '#ef4444' },
    attentionChevron: { fontSize: 12, color: '#ef4444' },
    attentionScroll: { marginTop: 8 },
    attentionCard: { width: 140, backgroundColor: 'rgba(30,41,59,0.9)', borderRadius: 10, padding: 10, marginRight: 8 },
    attentionBadge: { fontSize: 9, fontWeight: '700', color: '#fff', backgroundColor: '#ef4444', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, alignSelf: 'flex-start', marginBottom: 6 },
    attentionService: { fontSize: 13, fontWeight: '700', color: '#fff', textTransform: 'capitalize' },
    attentionAddr: { fontSize: 11, color: '#94a3b8', marginTop: 2 },

    // Queue
    queueContainer: { flex: 1 },
    listContent: { paddingBottom: 20 },
    empty: { alignItems: 'center', paddingVertical: 60 },
    emptyText: { fontSize: 14, color: '#64748b' },
    paginationTopRow: { alignItems: 'center', marginBottom: 8 },
    paginationTopCompact: { paddingVertical: 0 },

    // Mini Filter Button (for Needs Attention)
    miniFilterBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(71,85,105,0.3)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
    miniFilterText: { fontSize: 11, color: '#94a3b8', marginRight: 4 },
    miniFilterArrow: { fontSize: 10, color: '#94a3b8' },

    // Clean Sort Button
    cleanSortBtn: { paddingHorizontal: 4 },
    cleanSortText: { fontSize: 13, color: '#3b82f6', fontWeight: '500' },

    // Card Urgency Badge
    cardUrgencyBadge: { marginTop: 8, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: 'rgba(245,158,11,0.2)', borderRadius: 4, alignSelf: 'flex-start' },
    cardUrgencyEmergency: { backgroundColor: 'rgba(239,68,68,0.2)' },
    cardUrgencyText: { fontSize: 10, fontWeight: '700', color: '#f59e0b' },

    // Assign Buttons
    cardAssignBtn: { backgroundColor: 'rgba(59,130,246,0.2)', borderRadius: 8, paddingVertical: 6, alignItems: 'center', marginTop: 8 },
    cardAssignText: { fontSize: 12, fontWeight: '700', color: '#60a5fa' },
    compactAssignBtn: { backgroundColor: 'rgba(59,130,246,0.2)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
    compactAssignText: { fontSize: 10, fontWeight: '700', color: '#60a5fa' },

    // Card Pay Button
    cardPayBtn: { backgroundColor: '#22c55e', borderRadius: 8, paddingVertical: 8, alignItems: 'center', marginTop: 8 },
    cardPayText: { fontSize: 12, fontWeight: '700', color: '#fff' },

    // Create Order Styles (Dispatcher parity)
    createWrapper: { flex: 1 },
    createContainer: { flex: 1, padding: 16 },
    createScrollContent: { paddingBottom: 20 },
    createSections: { flex: 1 },
    formSection: { backgroundColor: 'rgba(30,41,59,0.8)', borderRadius: 16, padding: 16, marginBottom: 12 },
    formSectionLight: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0', shadowColor: '#000', shadowOffset: { height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
    formSectionTitle: { fontSize: 14, fontWeight: '700', color: '#fff', marginBottom: 12 },
    inputLabel: { fontSize: 10, fontWeight: '700', color: '#64748b', textTransform: 'uppercase', marginBottom: 4, marginTop: 8 },
    input: { backgroundColor: 'rgba(71,85,105,0.3)', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, color: '#fff', fontSize: 14 },
    inputError: { borderWidth: 1, borderColor: '#ef4444' },
    inputWithIcon: { position: 'relative' },
    inputWithPaste: { paddingRight: 44 },
    inFieldBtn: { position: 'absolute', right: 4, top: 4, bottom: 4, width: 36, backgroundColor: 'rgba(59,130,246,0.15)', borderRadius: 6, alignItems: 'center', justifyContent: 'center' },
    inFieldBtnText: { fontSize: 16, color: '#3b82f6' },
    textArea: { minHeight: 80, textAlignVertical: 'top' },
    pickerInput: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    pickerBtnText: { color: '#fff', fontSize: 14 },
    placeholderText: { color: '#64748b' },
    serviceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 8 },
    serviceBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, backgroundColor: 'rgba(71,85,105,0.3)', borderWidth: 1, borderColor: 'transparent' },
    serviceBtnActive: { backgroundColor: '#8b5cf6', borderColor: '#8b5cf6' },
    serviceBtnText: { fontSize: 12, fontWeight: '600', color: '#94a3b8' },
    serviceBtnTextActive: { color: '#fff' },
    urgencyRow: { flexDirection: 'row', gap: 8 },
    urgencyBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, backgroundColor: 'rgba(71,85,105,0.3)', alignItems: 'center', borderWidth: 1, borderColor: 'transparent' },
    urgencyBtnActive: { backgroundColor: '#3b82f6', borderColor: '#3b82f6' },
    urgencyText: { fontSize: 12, fontWeight: '600', color: '#94a3b8', textTransform: 'capitalize' },
    urgencyTextActive: { color: '#fff' },
    plannedPickerContainer: { marginTop: 8, gap: 8 },
    plannedTimeRow: { flexDirection: 'row', gap: 8 },
    plannedDateInput: { flex: 1 },
    plannedTimeInput: { flex: 1 },
    webPickerInput: { justifyContent: 'center', paddingVertical: 6 },
    datePickerButton: { justifyContent: 'center' },
    datePickerText: { color: '#fff' },
    pricingRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
    pricingBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, backgroundColor: 'rgba(71,85,105,0.3)', alignItems: 'center' },
    pricingBtnActive: { backgroundColor: '#22c55e' },
    pricingBtnText: { fontSize: 12, fontWeight: '600', color: '#fff' },
    charCounter: { position: 'absolute', bottom: 8, right: 12, fontSize: 10, color: '#64748b', fontWeight: '500' },
    createFooter: { backgroundColor: 'rgba(30,41,59,0.95)', borderRadius: 16, padding: 16, marginTop: 12 },
    confirmRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: '#64748b', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
    checkboxChecked: { backgroundColor: '#3b82f6', borderColor: '#3b82f6' },
    fixedBottomBar: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#1e293b', borderTopWidth: 1, borderTopColor: 'rgba(71,85,105,0.3)', padding: 12, paddingBottom: Platform.OS === 'ios' ? 28 : 12 },
    fixedBottomBarLight: { backgroundColor: '#fff', borderTopColor: '#e2e8f0' },
    bottomBarButtons: { flexDirection: 'row', gap: 12 },
    bottomClearBtn: { paddingVertical: 14, paddingHorizontal: 20, borderRadius: 10, backgroundColor: 'rgba(71,85,105,0.3)', alignItems: 'center' },
    bottomClearBtnText: { fontSize: 14, fontWeight: '600', color: '#94a3b8' },
    bottomPublishBtn: { flex: 1, paddingVertical: 14, borderRadius: 10, backgroundColor: '#3b82f6', alignItems: 'center' },
    bottomPublishBtnDisabled: { backgroundColor: '#475569', opacity: 0.7 },
    bottomPublishBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
    successContainer: { alignItems: 'center', paddingVertical: 60 },
    successIcon: { fontSize: 64, color: '#22c55e', marginBottom: 16 },
    successTitle: { fontSize: 24, fontWeight: '700', color: '#fff', marginBottom: 8 },
    successId: { fontSize: 16, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', color: '#94a3b8', marginBottom: 24 },
    successBtn: { backgroundColor: '#3b82f6', paddingHorizontal: 24, paddingVertical: 14, borderRadius: 10, marginBottom: 12 },
    successBtnText: { fontSize: 14, fontWeight: '600', color: '#fff' },
    successBtnAlt: { paddingHorizontal: 24, paddingVertical: 14 },
    successBtnAltText: { fontSize: 14, fontWeight: '600', color: '#3b82f6' },
    successDivider: { marginTop: 24, paddingTop: 16, borderTopWidth: 1, borderTopColor: 'rgba(71,85,105,0.3)', width: '100%', alignItems: 'center' },
    successDividerText: { fontSize: 12, color: '#64748b', fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
    successButtonRow: { flexDirection: 'row', gap: 12, marginTop: 16, width: '100%' },
    successKeepLocationBtn: { flex: 1, paddingVertical: 14, borderRadius: 12, backgroundColor: '#3b82f6', alignItems: 'center' },
    successKeepLocationText: { color: '#fff', fontSize: 14, fontWeight: '700' },
    checkmark: { color: '#fff', fontSize: 14, fontWeight: '700' },
    confirmLabel: { fontSize: 13, fontWeight: '600', color: '#fff' },
    createButtons: { flexDirection: 'row', gap: 8 },
    clearBtn: { width: 50, borderRadius: 10, backgroundColor: 'rgba(71,85,105,0.3)', justifyContent: 'center', alignItems: 'center', paddingVertical: 14 },
    clearBtnText: { fontSize: 18, color: '#fff' },
    publishBtn: { flex: 1, borderRadius: 10, backgroundColor: '#3b82f6', justifyContent: 'center', alignItems: 'center', paddingVertical: 14 },
    publishBtnDisabled: { backgroundColor: '#334155', opacity: 0.6 },
    publishBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
    errorText: { fontSize: 10, color: '#ef4444', marginTop: 4 },

    // Light Mode Card Style
    cardLight: { backgroundColor: '#ffffff', borderColor: '#e2e8f0', borderWidth: 1, shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2, elevation: 2 },

    // Picker Modal Styles
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', paddingHorizontal: 20, zIndex: 9999 },
    pickerContent: { width: '85%', maxHeight: '60%', backgroundColor: '#1e293b', borderRadius: 16, padding: 20, alignSelf: 'center' },
    pickerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, borderBottomWidth: 1, borderBottomColor: '#334155', paddingBottom: 12 },
    pickerTitle: { fontSize: 18, fontWeight: '700', color: '#fff' },
    pickerClose: { fontSize: 20, color: '#94a3b8', padding: 4 },
    pickerScroll: { maxHeight: 400 },
    pickerOption: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: '#334155' },
    pickerOptionActive: { backgroundColor: 'rgba(59,130,246,0.1)', borderRadius: 8 },
    pickerOptionText: { fontSize: 16, color: '#cbd5e1' },
    pickerOptionInfo: { flex: 1, paddingRight: 12 },
    pickerOptionSubText: { fontSize: 12, color: '#94a3b8', marginTop: 2 },
    pickerOptionSubTextActive: { color: '#bfdbfe' },
    pickerOptionTextActive: { color: '#3b82f6', fontWeight: '600' },
    pickerCheck: { color: '#3b82f6', fontSize: 16, fontWeight: '700' },
    pickerSearchInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        minHeight: 44,
        borderRadius: 12,
        paddingHorizontal: 12,
        backgroundColor: 'rgba(71,85,105,0.3)',
        marginBottom: 12,
    },
    pickerSearchInput: {
        flex: 1,
        color: '#fff',
        fontSize: 14,
        lineHeight: 20,
        paddingVertical: 10,
        borderWidth: 0,
        ...(Platform.OS === 'web' ? { outlineStyle: 'none', outlineWidth: 0 } : {}),
    },
    statusTabText: { fontSize: 12, fontWeight: '600', color: '#94a3b8' },
    statusTabTextActive: { color: '#fff' },
    filterTab: {
        // Legacy fallback if needed, but we'll switch to statusTab
        paddingVertical: 8,
        paddingHorizontal: 16,
        marginRight: 8,
        borderRadius: 20,
        backgroundColor: 'rgba(71,85,105,0.3)',
        borderWidth: 1,
        borderColor: 'rgba(51,65,85,0.5)'
    },
    filterTabActive: {
        backgroundColor: '#3b82f6',
        borderColor: '#3b82f6',
    },
    filterTabText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#94a3b8',
    },
    filterTabTextActive: {
        color: '#fff',
        fontWeight: '600',
    },

    // Edit Button
    editBtn: {
        paddingVertical: 6,
        paddingHorizontal: 16,
        backgroundColor: '#e2e8f0',
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 80,
        borderWidth: 1,
        borderColor: '#cbd5e1'
    },
    editBtnText: { fontSize: 13, fontWeight: '600', color: '#3b82f6' },
    editBtnTextActive: { color: '#fff', fontWeight: '600' },

    // People Page Styles
    tabBtn: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 8 },
    tabBtnActive: { backgroundColor: '#3b82f6' },
    tabBtnText: { color: '#94a3b8', fontWeight: '600', fontSize: 13 },
    tabBtnTextActive: { color: '#fff' },
    miniActionBtn: { paddingVertical: 6, paddingHorizontal: 8, borderRadius: 6, alignItems: 'center', justifyContent: 'center', minWidth: 64, maxWidth: '100%' },

    // Light Mode Styles
    headerLight: { borderBottomColor: '#cbd5e1', backgroundColor: '#fff' },
    sidebarContainerLight: { backgroundColor: '#fff', borderRightColor: '#cbd5e1' },
    sidebarHeaderLight: { borderBottomColor: '#f1f5f9' },
    textDark: { color: '#0f172a' },
    textSecondary: { color: '#64748b' },
    btnLight: { backgroundColor: '#f1f5f9' },
    sidebarFooterLight: { borderTopColor: '#f1f5f9' },
    sidebarBtnLight: { backgroundColor: '#f1f5f9', borderColor: '#e2e8f0' },
    cardLight: { backgroundColor: '#fff', borderColor: '#e2e8f0' },
    sectionHeaderLight: { backgroundColor: '#fff', borderBottomColor: '#f1f5f9' },
    inputLight: { backgroundColor: '#f8fafc', borderColor: '#e2e8f0', color: '#0f172a' },
    serviceIconLight: { backgroundColor: '#f1f5f9' },
    mainContentLight: { backgroundColor: '#f8fafc' },
    loadingContainerLight: { backgroundColor: '#f8fafc' },

    // Light Mode Element Styles
    orderCardLight: { backgroundColor: '#fff', borderColor: '#e2e8f0' },
    compactRowLight: { backgroundColor: '#fff' },
    listItemCardLight: { backgroundColor: '#fff', borderColor: '#e2e8f0' },
    searchInputWrapperLight: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0' },
    searchInputTextLight: { color: '#0f172a' },
    textLight: { color: '#0f172a' },
    chartCardLight: { backgroundColor: '#fff', borderColor: '#e2e8f0' },
    filterDropdownLight: { backgroundColor: '#fff', borderColor: '#e2e8f0' },
    filterDropdownTextLight: { color: '#0f172a' },
    viewToggleBtnLight: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0' },
    filterShowBtnLight: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0' },
    filterShowBtnTextLight: { color: '#64748b' },
    pointerEventsNone: { pointerEvents: 'none' },

    // Service Card Grid
    serviceCard: {
        width: '48%',
        backgroundColor: '#1e293b',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#334155',
    },
    serviceIcon: {
        width: 32,
        height: 32,
        borderRadius: 8,
        backgroundColor: '#334155',
        alignItems: 'center',
        justifyContent: 'center',
    },
    serviceName: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 13,
    },
    serviceSubName: {
        color: '#94a3b8',
        fontSize: 11,
    },
    valueText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
    },

    // ============================================
    // SETTINGS PAGE STYLES
    // ============================================
    settingsSection: {
        marginBottom: 8,
    },
    settingsSectionLight: {
        backgroundColor: 'transparent',
    },
    settingsSectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 20,
        flexWrap: 'wrap',
        gap: 16,
    },
    settingsSectionTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        flex: 1,
        minWidth: 220,
    },
    settingsSectionIcon: {
        width: 44,
        height: 44,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    settingsSectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#fff',
    },
    settingsSectionSubtitle: {
        fontSize: 13,
        color: '#64748b',
        marginTop: 2,
    },
    settingsSearchRow: {
        marginBottom: 12,
    },
    settingsActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginLeft: 'auto',
        flexShrink: 0,
    },
    settingsActionRowStacked: {
        width: '100%',
        justifyContent: 'flex-end',
        marginLeft: 0,
        flexBasis: '100%',
    },
    settingsActionGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        flexWrap: 'wrap',
    },
    settingsBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        height: 44,
        paddingVertical: 0,
        paddingHorizontal: 16,
        borderRadius: 10,
        minWidth: 160,
        justifyContent: 'center',
    },
    settingsBtnPrimary: {
        backgroundColor: '#22c55e',
    },
    settingsBtnSecondary: {
        backgroundColor: '#334155',
    },
    settingsBtnSecondaryLight: {
        backgroundColor: '#e2e8f0',
    },
    settingsBtnOutline: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#3b82f6',
    },
    settingsBtnOutlineLight: {
        backgroundColor: 'transparent',
        borderColor: '#3b82f6',
    },
    settingsBtnText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#94a3b8',
    },
    settingsCard: {
        backgroundColor: '#1e293b',
        borderRadius: 16,
        padding: 24,
        borderWidth: 1,
        borderColor: '#334155',
    },
    settingsCardLight: {
        backgroundColor: '#fff',
        borderColor: '#e2e8f0',
    },
    settingsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 24,
    },
    settingsGridItem: {
        width: '48%',
        minWidth: 280,
    },
    settingsFieldHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 4,
    },
    settingsFieldLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
    },
    settingsFieldHint: {
        fontSize: 12,
        color: '#64748b',
        marginBottom: 12,
    },
    settingsFieldValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#fff',
    },
    settingsFieldUnit: {
        fontSize: 14,
        fontWeight: '500',
        color: '#64748b',
    },
    settingsInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    settingsInput: {
        flex: 1,
        backgroundColor: '#0f172a',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#334155',
        color: '#fff',
        padding: 14,
        fontSize: 16,
        fontWeight: '600',
    },
    settingsInputLight: {
        backgroundColor: '#f8fafc',
        borderColor: '#e2e8f0',
        color: '#0f172a',
    },
    settingsInputSuffix: {
        fontSize: 14,
        fontWeight: '600',
        color: '#64748b',
        minWidth: 40,
    },
    settingsDivider: {
        height: 1,
        backgroundColor: '#334155',
        marginVertical: 32,
    },
    settingsDividerLight: {
        backgroundColor: '#e2e8f0',
    },
    settingsEmptyState: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
        backgroundColor: '#1e293b',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#334155',
        borderStyle: 'dashed',
    },
    settingsEmptyStateLight: {
        backgroundColor: '#f8fafc',
        borderColor: '#cbd5e1',
    },
    settingsEmptyText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#94a3b8',
        marginTop: 16,
    },
    settingsEmptyHint: {
        fontSize: 13,
        color: '#64748b',
        marginTop: 4,
    },
    compactList: {
        marginTop: 12,
        maxHeight: 320,
    },
    collapseBtn: {
        width: 38,
        height: 38,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#334155',
        backgroundColor: 'rgba(71,85,105,0.3)',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 10,
    },
    collapseBtnLight: {
        backgroundColor: '#f1f5f9',
        borderColor: '#e2e8f0',
    },
    togglePill: {
        alignSelf: 'flex-start',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 999,
    },
    toggleActive: {
        backgroundColor: 'rgba(34,197,94,0.15)',
        borderWidth: 1,
        borderColor: 'rgba(34,197,94,0.35)',
    },
    toggleInactive: {
        backgroundColor: 'rgba(239,68,68,0.15)',
        borderWidth: 1,
        borderColor: 'rgba(239,68,68,0.35)',
    },
    toggleText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#94a3b8',
    },
    pillRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    pillBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#334155',
        backgroundColor: 'rgba(71,85,105,0.2)',
    },
    pillBtnLight: {
        borderColor: '#cbd5e1',
        backgroundColor: '#f1f5f9',
    },
    pillBtnActive: {
        borderColor: 'rgba(59,130,246,0.5)',
        backgroundColor: 'rgba(59,130,246,0.2)',
    },
    pillBtnActiveLight: {
        borderColor: 'rgba(37,99,235,0.45)',
        backgroundColor: '#dbeafe',
    },
    pillText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#cbd5e1',
    },
    pillTextLight: {
        color: '#475569',
    },
    pillTextActive: {
        color: '#93c5fd',
    },
    pillTextActiveLight: {
        color: '#1d4ed8',
    },

    // Service Types Grid (New Design)
    serviceTypesGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
    },
    // Service Types List (Responsive alternative to grid)
    serviceTypesList: {
        gap: 8,
    },
    serviceTypeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#1e293b',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#334155',
    },
    serviceTypeRowLight: {
        backgroundColor: '#fff',
        borderColor: '#e2e8f0',
    },
    serviceTypeRowInfo: {
        flex: 1,
        marginRight: 16,
    },
    serviceTypeRowName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 2,
    },
    serviceTypeRowMeta: {
        fontSize: 12,
        color: '#64748b',
    },
    serviceTypeRowActions: {
        flexDirection: 'row',
        gap: 8,
    },
    serviceTypeRowBtn: {
        width: 36,
        height: 36,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    serviceTypeCard: {
        width: 'calc(25% - 12px)',
        minWidth: 220,
        backgroundColor: '#1e293b',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#334155',
    },
    serviceTypeCardLight: {
        backgroundColor: '#fff',
        borderColor: '#e2e8f0',
    },
    serviceTypeHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    serviceTypeIcon: {
        width: 52,
        height: 52,
        borderRadius: 14,
        backgroundColor: '#334155',
        alignItems: 'center',
        justifyContent: 'center',
    },
    serviceTypeIconLight: {
        backgroundColor: '#f1f5f9',
    },
    serviceTypeStatusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 20,
    },
    serviceTypeStatusDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    serviceTypeStatusText: {
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    serviceTypeContent: {
        marginBottom: 16,
    },
    serviceTypeName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 4,
    },
    serviceTypeSubName: {
        fontSize: 13,
        color: '#94a3b8',
        marginBottom: 6,
    },
    serviceTypeCode: {
        fontSize: 11,
        color: '#64748b',
        fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    serviceTypeActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 8,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#334155',
    },
    serviceTypeActionBtn: {
        width: 36,
        height: 36,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    serviceTypeActionBtnLight: {
        backgroundColor: '#f1f5f9',
    },
    serviceTypeEditBtn: {
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
    },
    serviceTypeDeleteBtn: {
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
    },

    // ============================================
    // SIDEBAR DRAWER STYLES (Service Type Form)
    // ============================================
    sidebarDrawerOverlay: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    sidebarDrawerBackdrop: {
        flex: 1,
    },
    sidebarDrawerContent: {
        width: 420,
        maxWidth: '100%', // Prevent overflow on small screens
        backgroundColor: '#0f172a',
        height: '100%',
        borderLeftWidth: 1,
        borderLeftColor: '#1e293b',
        shadowColor: '#000',
        shadowOffset: { width: -4, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 10,
    },
    sidebarDrawerContentLight: {
        backgroundColor: '#fff',
        borderLeftColor: '#e2e8f0',
    },
    sidebarDrawerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#1e293b',
    },
    sidebarDrawerHeaderLight: {
        borderBottomColor: '#f1f5f9',
    },
    sidebarDrawerIconWrapper: {
        width: 44,
        height: 44,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sidebarDrawerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
    },
    sidebarDrawerSubtitle: {
        fontSize: 13,
        color: '#64748b',
        marginTop: 2,
    },
    sidebarDrawerCloseBtn: {
        width: 40,
        height: 40,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(71, 85, 105, 0.3)',
    },
    sidebarDrawerCloseBtnLight: {
        backgroundColor: '#f1f5f9',
    },
    sidebarDrawerBody: {
        flex: 1,
        padding: 20,
    },
    sidebarFormGroup: {
        marginBottom: 0,
    },
    sidebarFormLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 8,
    },
    sidebarFormInput: {
        backgroundColor: '#1e293b',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#334155',
        color: '#fff',
        padding: 14,
        fontSize: 15,
    },
    sidebarFormInputLight: {
        backgroundColor: '#f8fafc',
        borderColor: '#e2e8f0',
        color: '#0f172a',
    },
    sidebarFormInputDisabled: {
        opacity: 0.5,
        backgroundColor: '#0f172a',
    },
    sidebarFormSection: {
        backgroundColor: '#1e293b',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#334155',
        gap: 16,
    },
    sidebarFormSectionLight: {
        backgroundColor: '#f8fafc',
        borderColor: '#e2e8f0',
    },
    sidebarFormSectionTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 4,
    },
    sidebarFormToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#1e293b',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#334155',
    },
    sidebarFormToggleLight: {
        backgroundColor: '#f8fafc',
        borderColor: '#e2e8f0',
    },
    sidebarFormToggleIcon: {
        width: 44,
        height: 44,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sidebarFormToggleLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
    },
    sidebarFormToggleHint: {
        fontSize: 12,
        color: '#64748b',
        marginTop: 2,
    },
    sidebarFormSwitch: {
        width: 52,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#334155',
        padding: 2,
        justifyContent: 'center',
    },
    sidebarFormSwitchActive: {
        backgroundColor: '#22c55e',
    },
    sidebarFormSwitchThumb: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#64748b',
    },
    sidebarFormSwitchThumbActive: {
        backgroundColor: '#fff',
        marginLeft: 24,
    },
    sidebarDrawerFooter: {
        flexDirection: 'row',
        gap: 12,
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: '#1e293b',
    },
    sidebarDrawerFooterLight: {
        borderTopColor: '#f1f5f9',
    },
    sidebarDrawerBtn: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sidebarDrawerBtnPrimary: {
        backgroundColor: '#22c55e',
    },
    sidebarDrawerBtnSecondary: {
        backgroundColor: '#1e293b',
        borderWidth: 1,
        borderColor: '#334155',
    },
    sidebarDrawerBtnSecondaryLight: {
        backgroundColor: '#f1f5f9',
        borderColor: '#e2e8f0',
    },
    sidebarDrawerBtnText: {
        fontSize: 15,
        fontWeight: '600',
    },
    // ============================================
    // ANALYTICS STYLES
    // ============================================
    analyticsFilterCard: {
        backgroundColor: '#1e293b',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#334155',
    },
    analyticsFilterHeader: {
        marginBottom: 12,
    },
    analyticsFilterTopRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        marginBottom: 10,
    },
    analyticsSectionLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 8,
    },
    analyticsRangeRow: {
        flexDirection: 'row',
        gap: 6,
    },
    analyticsRangeScroll: {
        flexGrow: 1,
        minWidth: 200,
    },
    analyticsRangeChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: 'rgba(71, 85, 105, 0.3)',
    },
    analyticsRangeChipActive: {
        backgroundColor: '#3b82f6',
    },
    analyticsRangeText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#94a3b8',
    },
    analyticsRangeTextActive: {
        color: '#fff',
    },
    analyticsFilterRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    analyticsPeopleFilterRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        marginTop: 12,
    },
    analyticsFilterPill: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: 'rgba(71, 85, 105, 0.3)',
        minWidth: 100,
    },
    analyticsFilterPillActive: {
        backgroundColor: 'rgba(59, 130, 246, 0.2)',
        borderWidth: 1,
        borderColor: '#3b82f6',
    },
    analyticsFilterPillLight: {
        backgroundColor: '#f1f5f9',
    },
    analyticsFilterPillRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    analyticsFilterPillText: {
        fontSize: 13,
        fontWeight: '500',
        color: '#cbd5e1',
    },
    analyticsClearBtn: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
    },
    analyticsClearBtnText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#ef4444',
    },
    analyticsCustomRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 12,
    },
    analyticsCustomButton: {
        flex: 1,
        backgroundColor: 'rgba(71, 85, 105, 0.3)',
        borderRadius: 8,
        padding: 12,
    },
    analyticsCustomButtonLight: {
        backgroundColor: '#f1f5f9',
    },
    analyticsCustomLabel: {
        fontSize: 11,
        color: '#64748b',
        marginBottom: 4,
    },
    analyticsCustomValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
    },
    analyticsCustomInput: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
        padding: 0,
    },
    analyticsCustomSeparator: {
        fontSize: 16,
        color: '#64748b',
    },
    analyticsSectionTabs: {
        flexDirection: 'row',
        gap: 6,
        marginBottom: 16,
    },
    analyticsSectionTab: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 10,
        backgroundColor: 'rgba(71, 85, 105, 0.3)',
    },
    analyticsSectionTabActive: {
        backgroundColor: '#3b82f6',
    },
    analyticsSectionTabText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#94a3b8',
    },
    analyticsSectionTabTextActive: {
        color: '#fff',
    },
    analyticsGranularityRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 12,
    },
    analyticsGranularityLabel: {
        fontSize: 13,
        color: '#64748b',
    },
    analyticsGranularityChips: {
        flexDirection: 'row',
        gap: 6,
    },
    analyticsGranularityChip: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 6,
        backgroundColor: 'rgba(71, 85, 105, 0.3)',
    },
    analyticsGranularityChipActive: {
        backgroundColor: '#22c55e',
    },
    analyticsGranularityText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#94a3b8',
    },
    analyticsGranularityTextActive: {
        color: '#fff',
    },
    analyticsChartGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
        marginBottom: 16,
    },
    analyticsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
        marginBottom: 16,
        alignItems: 'stretch',
    },
    analyticsRowItem: {
        flex: 1,
        minWidth: 320,
    },
    analyticsVisualGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
        marginBottom: 16,
    },
    analyticsOperationsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
        marginBottom: 16,
        alignItems: 'stretch',
    },
    analyticsOperationsStatus: {
        flex: 1,
        minWidth: 320,
    },
    analyticsOperationsStatusCard: {
        height: '100%',
    },
    analyticsOperationsMetrics: {
        flex: 1.4,
        minWidth: 360,
    },
    analyticsOperationsMetricsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    analyticsOperationsMetricItem: {
        flexBasis: '48%',
        minWidth: 220,
        flexGrow: 1,
    },
    analyticsStackedChartBlock: {
        padding: 8,
    },
    analyticsStackedCharts: {
        gap: 12,
    },
    analyticsStackedChartDivider: {
        height: 1,
        backgroundColor: 'rgba(148,163,184,0.2)',
    },
    analyticsFinancialMetricsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    analyticsFinancialMetricItem: {
        flexBasis: '48%',
        minWidth: 220,
        flexGrow: 1,
    },
    analyticsFinancialMetricsBlock: {
        flex: 1,
        justifyContent: 'space-between',
        alignSelf: 'stretch',
    },
    analyticsVisualCard: {
        backgroundColor: '#1c283d',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.25)',
        ...Platform.select({
            web: {
                boxShadow: '0 12px 24px rgba(15,23,42,0.25)',
            },
            ios: {
                shadowColor: '#0f172a',
                shadowOpacity: 0.25,
                shadowRadius: 12,
                shadowOffset: { width: 0, height: 6 },
            },
            android: {
                elevation: 4,
            },
        }),
    },
    analyticsDispatcherCard: {
        borderColor: 'rgba(59,130,246,0.45)',
        backgroundColor: '#1b2740',
    },
    analyticsMasterCard: {
        borderColor: 'rgba(59,130,246,0.35)',
        backgroundColor: '#1b2740',
    },
    analyticsPriceDistCard: {
        borderColor: 'rgba(14,165,233,0.35)',
        backgroundColor: '#1b263b',
    },
    analyticsVisualTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 12,
    },
    analyticsPriceDistHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 12,
        flexWrap: 'wrap',
        marginBottom: 6,
    },
    analyticsPriceDistMeta: {
        fontSize: 12,
        color: '#94a3b8',
        marginBottom: 6,
    },
    analyticsPriceDistControlRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 14,
    },
    analyticsPriceDistControlGroup: {
        minWidth: 160,
        flex: 1,
    },
    analyticsPriceDistControlLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: '#94a3b8',
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        marginBottom: 6,
    },
    analyticsPriceDistChipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
    },
    analyticsPriceDistChip: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 6,
        backgroundColor: 'rgba(71, 85, 105, 0.35)',
    },
    analyticsPriceDistChipLight: {
        backgroundColor: '#e2e8f0',
    },
    analyticsPriceDistChipActive: {
        backgroundColor: '#0ea5e9',
    },
    analyticsPriceDistChipDisabled: {
        opacity: 0.45,
    },
    analyticsPriceDistChipText: {
        fontSize: 11,
        fontWeight: '600',
        color: '#cbd5e1',
    },
    analyticsPriceDistChipTextLight: {
        color: '#334155',
    },
    analyticsPriceDistChipTextActive: {
        color: '#fff',
    },
    analyticsPriceDistChipTextDisabled: {
        color: '#94a3b8',
    },
    analyticsPriceDistBody: {
        flexDirection: 'column',
        gap: 12,
    },
    analyticsPriceDistChartWrap: {
        width: '100%',
        overflow: 'hidden',
    },
    analyticsPriceDistNotice: {
        fontSize: 11,
        color: '#94a3b8',
        marginTop: -6,
        marginBottom: 8,
    },
    analyticsPriceDistSummary: {
        backgroundColor: 'rgba(15,23,42,0.4)',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.2)',
        alignSelf: 'stretch',
    },
    analyticsPriceDistSummaryLight: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
    },
    analyticsPriceDistSummaryTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 10,
    },
    analyticsPriceDistStatsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        justifyContent: 'space-between',
        width: '100%',
    },
    analyticsPriceDistStat: {
        flexGrow: 0,
        flexBasis: '23%',
        minWidth: 200,
        maxWidth: '23%',
        backgroundColor: 'rgba(30,41,59,0.6)',
        borderRadius: 10,
        padding: 8,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.12)',
    },
    analyticsPriceDistStatHoverable: {
        ...Platform.select({
            web: {
                cursor: 'help',
            },
        }),
    },
    analyticsPriceDistStatLight: {
        backgroundColor: '#f8fafc',
        borderColor: '#e2e8f0',
    },
    analyticsPriceDistStatLabel: {
        fontSize: 10,
        color: '#94a3b8',
        marginBottom: 2,
    },
    analyticsPriceDistStatValue: {
        fontSize: 12,
        fontWeight: '600',
        color: '#fff',
    },
    analyticsPriceDistStatPrimary: {
        borderColor: 'rgba(56,189,248,0.45)',
        backgroundColor: 'rgba(14,165,233,0.18)',
    },
    analyticsPriceDistStatPrimaryLight: {
        borderColor: '#93c5fd',
        backgroundColor: '#dbeafe',
    },
    analyticsPriceDistStatValuePrimary: {
        color: '#38bdf8',
    },
    analyticsPriceDistStatValuePrimaryLight: {
        color: '#2563eb',
    },
    analyticsPriceDistNote: {
        fontSize: 11,
        color: '#94a3b8',
        marginTop: 6,
    },
    analyticsTitleWithTip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flexShrink: 1,
    },
    analyticsStatusHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 8,
        marginBottom: 8,
    },
    analyticsStatusTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
    },
    analyticsDispatcherHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
        flexWrap: 'wrap',
        marginBottom: 12,
    },
    analyticsDispatcherPill: {
        minWidth: 180,
        maxWidth: 260,
    },
    analyticsMetricGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'stretch',
        gap: 12,
        marginBottom: 16,
    },
    analyticsMetricGroup: {
        flexDirection: 'column',
        gap: 12,
        width: '100%',
        marginBottom: 16,
    },
    analyticsMetricRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    analyticsMetricRowItem: {
        flex: 1,
        minWidth: 220,
    },
    analyticsMetricCard: {
        backgroundColor: '#182235',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.22)',
        minHeight: 118,
        justifyContent: 'space-between',
        ...Platform.select({
            web: {
                boxShadow: '0 10px 20px rgba(15,23,42,0.22)',
            },
            ios: {
                shadowColor: '#0f172a',
                shadowOpacity: 0.2,
                shadowRadius: 10,
                shadowOffset: { width: 0, height: 5 },
            },
            android: {
                elevation: 3,
            },
        }),
    },
    analyticsMetricTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    analyticsMetricLabel: {
        fontSize: 13,
        fontWeight: '500',
        color: '#94a3b8',
        marginBottom: 4,
    },
    analyticsMetricLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flexWrap: 'wrap',
    },
    analyticsMetricValue: {
        fontSize: 22,
        fontWeight: '700',
        color: '#fff',
    },
    analyticsMetricSub: {
        fontSize: 11,
        color: '#94a3b8',
        marginTop: 6,
        minHeight: 14,
    },
    analyticsListGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'stretch',
        gap: 16,
        marginBottom: 16,
    },
    analyticsListCol: {
        alignSelf: 'stretch',
        display: 'flex',
    },
    analyticsListColWide: {
        flexGrow: 1,
        flexBasis: 0,
        minWidth: 280,
        alignSelf: 'stretch',
        display: 'flex',
    },
    analyticsListCard: {
        backgroundColor: '#182235',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.22)',
        flex: 1,
        minHeight: 168,
        ...Platform.select({
            web: {
                boxShadow: '0 10px 20px rgba(15,23,42,0.22)',
            },
            ios: {
                shadowColor: '#0f172a',
                shadowOpacity: 0.2,
                shadowRadius: 10,
                shadowOffset: { width: 0, height: 5 },
            },
            android: {
                elevation: 3,
            },
        }),
    },
    analyticsListHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    analyticsListTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flexShrink: 1,
        flexWrap: 'wrap',
    },
    analyticsListTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
    },
    analyticsListAction: {
        fontSize: 13,
        fontWeight: '600',
        color: '#3b82f6',
    },
    analyticsListItem: {
        flexDirection: 'column',
        alignItems: 'stretch',
        paddingVertical: 8,
        borderTopWidth: 1,
        borderTopColor: '#334155',
    },
    analyticsListRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 6,
    },
    analyticsListLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#cbd5e1',
    },
    analyticsListBar: {
        height: 4,
        backgroundColor: '#334155',
        borderRadius: 2,
        overflow: 'hidden',
    },
    analyticsListBarFill: {
        height: 4,
        backgroundColor: '#3b82f6',
        borderRadius: 2,
    },
    analyticsListValue: {
        fontSize: 13,
        fontWeight: '700',
        color: '#fff',
        textAlign: 'right',
        fontVariant: ['tabular-nums'],
        minWidth: 110,
    },
    analyticsListEmpty: {
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center',
        paddingVertical: 16,
    },
    analyticsMiniBars: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 2,
    },
    analyticsMiniBarTrack: {
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    analyticsMiniBar: {
        borderRadius: 2,
    },
    analyticsStatusStrip: {
        flexDirection: 'row',
        height: 8,
        borderRadius: 4,
        overflow: 'hidden',
        marginBottom: 10,
        backgroundColor: 'rgba(148,163,184,0.2)',
    },
    analyticsStatusStripEmpty: {
        backgroundColor: 'rgba(148,163,184,0.15)',
    },
    analyticsStatusStripEmptyFill: {
        flex: 1,
        backgroundColor: 'rgba(148,163,184,0.18)',
    },
    analyticsStatusSegment: {
        minWidth: 2,
    },
    analyticsStatusLegend: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 16,
        paddingBottom: 2,
        paddingRight: 6,
        marginTop: 4,
        marginBottom: 16,
    },
    analyticsStatusLegendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingRight: 6,
        flexBasis: '48%',
        flexGrow: 1,
        minWidth: 140,
    },
    analyticsStatusLegendMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    analyticsPieWrap: {
        alignItems: 'center',
        gap: 12,
        paddingTop: 4,
    },
    analyticsStatusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    analyticsStatusLegendText: {
        fontSize: 12,
        fontWeight: '500',
        color: '#cbd5e1',
        flexShrink: 1,
        maxWidth: 140,
    },
    analyticsStatusLegendCount: {
        fontSize: 12,
        fontWeight: '700',
        color: '#e2e8f0',
    },
    analyticsStatusLegendValue: {
        fontSize: 12,
        fontWeight: '600',
        color: '#94a3b8',
    },
    analyticsFunnelRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'flex-end',
        gap: 8,
    },
    analyticsFunnelItem: {
        alignItems: 'center',
        flex: 1,
    },
    analyticsFunnelBar: {
        width: '80%',
        borderRadius: 4,
        marginBottom: 6,
    },
    analyticsFunnelLabel: {
        fontSize: 10,
        fontWeight: '500',
        color: '#cbd5e1',
        textAlign: 'center',
    },
    analyticsFunnelValue: {
        fontSize: 11,
        fontWeight: '600',
        color: '#94a3b8',
    },
    analyticsChartCard: {
        backgroundColor: '#1e293b',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#334155',
    },
    analyticsChartBare: {
        paddingBottom: 6,
    },
    analyticsChartHeader: {
        marginBottom: 12,
    },
    analyticsChartTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
    },
    analyticsChartSubtitle: {
        fontSize: 12,
        color: '#64748b',
        marginTop: 2,
    },
    analyticsChartBars: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'flex-end',
        height: 100,
        gap: 4,
    },
    analyticsChartColumn: {
        flex: 1,
        alignItems: 'center',
    },
    analyticsChartValue: {
        fontSize: 10,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 4,
    },
    analyticsChartTrack: {
        width: '80%',
        backgroundColor: '#334155',
        borderRadius: 4,
        justifyContent: 'flex-end',
        alignItems: 'center',
        overflow: 'hidden',
        height: 78,
    },
    analyticsChartTrackLight: {
        backgroundColor: '#e2e8f0',
    },
    analyticsChartFill: {
        width: '100%',
        borderRadius: 4,
    },
    analyticsChartLabel: {
        fontSize: 9,
        color: '#64748b',
        marginTop: 6,
        textAlign: 'center',
    },
    analyticsTrendHint: {
        fontSize: 10,
        color: '#64748b',
        marginTop: 8,
        textAlign: 'center',
    },
    analyticsTrendSection: {
        marginTop: 16,
        gap: 12,
    },
    analyticsTrendHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
        flexWrap: 'wrap',
    },
    analyticsTrendTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#fff',
    },
    analyticsTrendRangeRow: {
        flexDirection: 'row',
        gap: 8,
    },
    analyticsTrendRangeBtn: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        backgroundColor: 'rgba(71,85,105,0.3)',
    },
    analyticsTrendRangeBtnActive: {
        backgroundColor: '#3b82f6',
    },
    analyticsTrendRangeBtnLight: {
        backgroundColor: '#e2e8f0',
    },
    analyticsTrendRangeBtnActiveLight: {
        backgroundColor: '#2563eb',
    },
    analyticsTrendRangeText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#cbd5f5',
    },
    analyticsTrendRangeTextActive: {
        color: '#fff',
    },
    analyticsTrendRangeTextLight: {
        color: '#475569',
    },
    analyticsTrendRangeTextActiveLight: {
        color: '#fff',
    },
    analyticsTrendCards: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    analyticsTrendCard: {
        flex: 1,
        minWidth: 260,
        backgroundColor: 'rgba(71,85,105,0.25)',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(71,85,105,0.4)',
    },
    analyticsTrendCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        gap: 8,
    },
    analyticsTrendCardTitle: {
        fontSize: 11,
        color: '#94a3b8',
        textTransform: 'uppercase',
    },
    analyticsTrendCardMeta: {
        fontSize: 10,
        color: '#94a3b8',
    },
    analyticsTrendEmptyText: {
        fontSize: 11,
        color: '#94a3b8',
        textAlign: 'center',
        paddingVertical: 12,
    },
    analyticsTrendArea: {
        height: 90,
    },
    analyticsTrendGrid: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 10,
        bottom: 18,
        justifyContent: 'space-between',
    },
    analyticsTrendGridLine: {
        height: 1,
        backgroundColor: 'rgba(148,163,184,0.15)',
    },
    analyticsTrendYAxis: {
        position: 'absolute',
        left: 0,
        top: 6,
        bottom: 18,
        justifyContent: 'space-between',
    },
    analyticsTrendDots: {
        flexDirection: 'row',
        height: 72,
        marginTop: 6,
        gap: 4,
        alignItems: 'flex-end',
    },
    analyticsTrendSlot: {
        flex: 1,
        height: 72,
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    analyticsTrendDot: {
        borderRadius: 999,
    },
    analyticsTrendAvgLine: {
        position: 'absolute',
        left: 0,
        right: 0,
        height: 1,
        backgroundColor: 'rgba(148,163,184,0.25)',
        borderStyle: 'dashed',
    },
    analyticsTrendAxis: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 6,
    },
    analyticsTrendAxisText: {
        fontSize: 10,
        color: '#94a3b8',
    },
    analyticsTrendAxisTextLight: {
        color: '#64748b',
    },
    analyticsBoxplotChart: {
        position: 'relative',
        width: '100%',
        overflow: 'hidden',
    },
    analyticsBoxplotRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    analyticsBoxplotYAxis: {
        width: 60,
        alignItems: 'center',
        justifyContent: 'center',
        paddingTop: 10,
    },
    analyticsBoxplotYAxisText: {
        fontSize: 11,
        color: '#94a3b8',
        textAlign: 'center',
        lineHeight: 14,
    },
    analyticsBoxplotYAxisTextLight: {
        color: '#64748b',
    },
    analyticsBoxplotHitRow: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
        flexDirection: 'row',
    },
    analyticsBoxplotHit: {
        height: '100%',
        backgroundColor: 'transparent',
    },
    analyticsBoxplotLabels: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
        gap: 4,
        minHeight: 56,
    },
    analyticsBoxplotLabel: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 4,
    },
    analyticsBoxplotLabelText: {
        fontSize: 10,
        color: '#94a3b8',
    },
    analyticsBoxplotLabelTextRotated: {
        transform: [{ rotate: '-90deg' }],
        width: 70,
        textAlign: 'center',
        fontSize: 9,
        lineHeight: 10,
    },
    analyticsTrendTooltip: {
        position: 'absolute',
        backgroundColor: 'rgba(15,23,42,0.95)',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.3)',
        zIndex: 2000,
    },
    analyticsTrendTooltipLight: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
    },
    analyticsTrendTooltipTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 6,
    },
    analyticsTrendTooltipText: {
        fontSize: 11,
        color: '#cbd5f5',
    },
    analyticsPriceDistTooltip: {
        position: 'absolute',
        backgroundColor: 'rgba(15,23,42,0.96)',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.3)',
        zIndex: 2000,
    },
    analyticsPriceDistTooltipLight: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
    },
    analyticsPriceDistTooltipTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 6,
    },
    analyticsPriceDistTooltipRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 8,
        marginBottom: 2,
    },
    analyticsPriceDistTooltipLabel: {
        fontSize: 10,
        color: '#cbd5e1',
    },
    analyticsPriceDistTooltipValue: {
        fontSize: 10,
        fontWeight: '600',
        color: '#fff',
    },
    analyticsPriceDistTooltipNote: {
        fontSize: 10,
        color: '#f59e0b',
        marginTop: 4,
    },
    analyticsStatusMixTooltip: {
        position: 'absolute',
        backgroundColor: 'rgba(15,23,42,0.96)',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.3)',
        zIndex: 2000,
    },
    analyticsStatusMixTooltipLight: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
    },
    analyticsStatusMixTooltipHead: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 6,
    },
    analyticsStatusMixTooltipDot: {
        width: 8,
        height: 8,
        borderRadius: 999,
    },
    analyticsStatusMixTooltipTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: '#fff',
    },
    analyticsStatusMixTooltipText: {
        fontSize: 11,
        color: '#cbd5e1',
        marginTop: 2,
    },
    analyticsPriceDistMetricTooltip: {
        position: 'absolute',
        backgroundColor: 'rgba(15,23,42,0.96)',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.3)',
        zIndex: 2000,
    },
    analyticsPriceDistMetricTooltipLight: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
    },
    analyticsPriceDistMetricTooltipTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: '#fff',
    },
    analyticsPriceDistMetricTooltipValue: {
        marginTop: 4,
        fontSize: 13,
        fontWeight: '700',
        color: '#38bdf8',
    },
    analyticsPriceDistMetricTooltipText: {
        marginTop: 8,
        fontSize: 11,
        color: '#cbd5e1',
        lineHeight: 16,
    },
    analyticsModalCard: {
        backgroundColor: '#1e293b',
        borderRadius: 16,
        padding: 20,
        width: 400,
        maxWidth: '90%',
        maxHeight: '80%',
        borderWidth: 1,
        borderColor: '#334155',
        alignSelf: 'center',
        ...Platform.select({
            web: {
                margin: 'auto',
                boxShadow: '0 24px 40px rgba(15,23,42,0.35)',
            },
        }),
    },
    analyticsModalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 16,
    },
    analyticsDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: '#334155',
    },
    analyticsTooltip: {
        position: 'absolute',
        backgroundColor: 'rgba(15,23,42,0.96)',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.3)',
        zIndex: 2000,
        maxWidth: 260,
    },
    analyticsTooltipLight: {
        backgroundColor: '#ffffff',
        borderColor: '#e2e8f0',
    },
    analyticsTooltipText: {
        fontSize: 12,
        color: '#e2e8f0',
        lineHeight: 16,
    },
    infoTipWrap: {
        position: 'relative',
        zIndex: 2,
    },
    infoTipIcon: {
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: 'rgba(71,85,105,0.4)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    infoTipIconLight: {
        backgroundColor: '#e2e8f0',
    },
    infoTipText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#cbd5e1',
    },
    infoTipBubble: {
        position: 'absolute',
        top: 22,
        left: 0,
        zIndex: 10,
        maxWidth: 240,
        padding: 10,
        borderRadius: 10,
        backgroundColor: '#0f172a',
        borderWidth: 1,
        borderColor: 'rgba(148,163,184,0.4)',
    },
    infoTipBubbleText: {
        fontSize: 11,
        color: '#e2e8f0',
        lineHeight: 16,
    },
    analyticsModalActions: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 16,
    },
    analyticsModalPrimary: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        backgroundColor: '#3b82f6',
        alignItems: 'center',
    },
    analyticsModalPrimaryText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
    },
    analyticsModalSecondary: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        backgroundColor: 'rgba(71, 85, 105, 0.3)',
        alignItems: 'center',
    },
    analyticsModalSecondaryText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#94a3b8',
    },
});

export default styles;
